(function(){
'use strict';
var root=document.querySelector('[data-verbum-app]');if(!root)return;
var live={dirty:false,busy:false,workspace:null,form:null,id:null,timer:null,saveState:'saved',editVersion:0,savePromise:null};
var genres=['Formação','Ensaio','Romance','Biografia','Devocional','Manual','Catequético','Acadêmico','Testemunho','Meditação','Não ficção','Ficção','Outro'];
var languages=['Português (BR)','Português (PT)','Espanhol','Inglês','Italiano','Francês','Outro'];
var colors=['#15677a','#9b6b2f','#4f825e','#8b38d1','#c41f25','#244bb8','#bf1f62','#187a6f','#c84b0a','#4d3dc4'];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function cfg(){return window.VerbumStudioConfig||{apiRoot:'/wp-json/verbum/v1',nonce:''};}
function api(path,opt){opt=opt||{};var c=cfg(),h={'X-WP-Nonce':c.nonce||''},body=opt.body,fd=typeof FormData!=='undefined'&&body instanceof FormData;if(body!==undefined&&!fd)h['Content-Type']='application/json';return fetch(c.apiRoot+path,{method:opt.method||'GET',credentials:'same-origin',headers:h,body:body===undefined?undefined:(fd?body:JSON.stringify(body))}).then(function(r){return r.json().then(function(p){if(!r.ok||!p.success)throw new Error(p&&p.error?p.error.message:'Erro na API.');return p.data;});});}
function route(){var p=new URLSearchParams(location.search);return{id:p.get('verbum_work'),stage:p.get('verbum_stage')||'identification'};}
function initialForm(w){var b=w.book||{};return{title:b.title||'',subtitle:b.subtitle||'',genre:b.genre||'',language:b.language==='Português'?'Português (BR)':(b.language||''),synopsis:b.synopsis||'',color:b.color||''};}
function options(items,current){var a=items.slice();if(current&&a.indexOf(current)<0)a.unshift(current);return a.map(function(x){return'<option value="'+esc(x)+'"'+(x===current?' selected':'')+'>'+esc(x)+'</option>';}).join('');}
function essential(){var f=live.form||{};return[
  {key:'title',label:'Título provisório',completed:String(f.title||'').trim()!==''},
  {key:'genre',label:'Gênero',completed:String(f.genre||'').trim()!==''},
  {key:'language',label:'Idioma',completed:String(f.language||'').trim()!==''}
];}
function optional(){var f=live.form||{},b=live.workspace&&live.workspace.book||{};return[
  {key:'subtitle',label:'Subtítulo provisório',completed:String(f.subtitle||'').trim()!==''},
  {key:'synopsis',label:'Descrição inicial',completed:String(f.synopsis||'').trim()!==''},
  {key:'cover',label:'Capa provisória',completed:!!b.coverUrl},
  {key:'color',label:'Cor de identificação',completed:String(f.color||'').trim()!==''}
];}
function ready(){return essential().every(function(x){return x.completed;});}
function progressHtml(){var items=essential(),done=items.filter(function(x){return x.completed;}).length,p=Math.round(done/items.length*100),opts=optional(),missing=items.filter(function(x){return !x.completed;});return'<div class="verbum-progress-heading"><h3>'+(done===3?'Identificação pronta para continuar':'Progresso da Etapa')+'</h3><strong>'+p+'%</strong></div><div class="verbum-progress-track"><span style="width:'+p+'%"></span></div><p>'+done+' de 3 itens essenciais preenchidos</p><div class="verbum-identification-checklist">'+items.map(function(x){return'<div class="'+(x.completed?'is-completed':'')+'"><span>'+(x.completed?'✓':'')+'</span><span>'+esc(x.label)+'</span></div>';}).join('')+'</div>'+(missing.length?'<div class="verbum-identification-missing"><strong>Preencha para continuar:</strong>'+missing.map(function(x){return'<span>'+esc(x.label)+'</span>';}).join('')+'</div>':'')+'<div class="verbum-identification-optional-progress"><strong>Opcionais preenchidos</strong>'+opts.map(function(x){return'<div class="'+(x.completed?'is-completed':'')+'"><span>'+(x.completed?'✓':'○')+'</span><span>'+esc(x.label)+'</span></div>';}).join('')+'</div>';}
function pageHtml(){var f=live.form,b=live.workspace.book,cover=b.coverUrl||'';return'<div class="verbum-identification-heading"><h2>Identificação da Obra</h2><p>Cadastre as informações essenciais e a identidade visual inicial do projeto. As decisões editoriais aprofundadas serão desenvolvidas na Fundação da Obra.</p></div><div class="verbum-identification-layout"><form class="verbum-identification-card" data-id-form><section class="verbum-identification-section"><div class="verbum-identification-section-title"><span>1</span><div><h3>Informações essenciais</h3><p>Estes três campos são necessários para continuar.</p></div></div><div class="verbum-identification-grid">'+
'<label class="verbum-identification-span-2"><span>Título provisório <b>*</b></span><input name="title" value="'+esc(f.title)+'" autocomplete="off"></label>'+
'<label><span>Gênero <b>*</b></span><select name="genre"><option value="">Selecione...</option>'+options(genres,f.genre)+'</select></label>'+
'<label><span>Idioma <b>*</b></span><select name="language"><option value="">Selecione...</option>'+options(languages,f.language)+'</select></label></div></section>'+
'<section class="verbum-identification-section is-optional"><div class="verbum-identification-section-title"><span>2</span><div><h3>Informações complementares</h3><p>Campos opcionais que podem ser ajustados a qualquer momento.</p></div></div><div class="verbum-identification-grid">'+
'<label class="verbum-identification-span-2"><span>Subtítulo provisório <em>Opcional</em></span><input name="subtitle" value="'+esc(f.subtitle)+'" autocomplete="off"></label>'+
'<label class="verbum-identification-span-2"><span>Descrição inicial da obra <em>Opcional</em></span><textarea name="synopsis" rows="5">'+esc(f.synopsis)+'</textarea><small>Registre brevemente a ideia do livro. Este texto poderá ser revisto durante o desenvolvimento.</small></label>'+
'<div class="verbum-cover-field"><span class="verbum-field-label">Capa provisória <em>Opcional</em></span><div class="verbum-cover-editor"><div class="verbum-cover-preview" style="background:'+esc(f.color||'#15677a')+'">'+(cover?'<img src="'+esc(cover)+'" alt="">':'<span>V</span>')+'</div><button type="button" class="verbum-cover-dropzone" data-cover-pick><strong>↻</strong><span>'+(cover?'Arraste para substituir ou clique para trocar a imagem':'Arraste uma imagem ou clique para enviar a capa provisória')+'</span></button></div><div class="verbum-cover-actions"><button type="button" class="verbum-secondary-button" data-cover-pick>'+(cover?'Trocar imagem':'Enviar capa')+'</button><button type="button" class="verbum-text-button is-danger" data-cover-remove '+(!cover?'disabled':'')+'>Remover</button></div><input type="file" class="sr-only" accept="image/jpeg,image/png,image/webp" data-cover-input></div>'+
'<div class="verbum-color-field"><span class="verbum-field-label">Cor de identificação no sistema <em>Opcional</em></span><div class="verbum-color-palette">'+colors.map(function(x){return'<button type="button" aria-label="Selecionar cor '+x+'" class="'+(f.color===x?'is-selected':'')+'" style="background:'+x+'" data-color="'+x+'"></button>';}).join('')+'</div></div></div></section><p class="verbum-identification-message" data-id-message hidden></p></form><aside class="verbum-identification-progress">'+progressHtml()+'</aside></div>';}
function payload(){var f=live.form;return{title:String(f.title||'').trim(),subtitle:String(f.subtitle||'').trim(),genre:f.genre||'',language:f.language||'',synopsis:String(f.synopsis||'').trim(),color:f.color||''};}
function msg(text,error){var n=document.querySelector('[data-id-message]');if(!n)return;n.hidden=!text;n.textContent=text||'';n.classList.toggle('is-error',!!error);}
function saveLabel(){return live.saveState==='saving'?'Salvando...':live.saveState==='error'?'Erro ao salvar':'Alterações salvas';}
function footer(){var n=document.querySelector('.verbum-workspace-footer');if(!n)return;n.classList.add('is-first-stage');n.innerHTML='<span class="verbum-workspace-footer-spacer" aria-hidden="true"></span><div class="verbum-workspace-save-actions"><span class="verbum-save-state is-'+live.saveState+'" data-save-state>'+saveLabel()+'</span><button type="button" class="verbum-primary-button" data-continue '+((!ready()||live.busy)?'disabled':'')+'>Continuar para Fundação ›</button></div>';var c=n.querySelector('[data-continue]');if(c)c.onclick=function(){complete();};}
function refreshProgress(){var stage=document.querySelector('.verbum-identification-stage');if(stage){var p=stage.querySelector('.verbum-identification-progress');if(p)p.innerHTML=progressHtml();}footer();}
function syncHeader(updated){if(root.__vs){root.__vs.workspace=updated;if(root.__vs.library&&root.__vs.library.books)root.__vs.library.books=root.__vs.library.books.map(function(b){return b.id===updated.book.id?updated.book:b;});}var t=document.querySelector('.verbum-work-title h1'),s=document.querySelector('.verbum-work-title p'),c=document.querySelector('.verbum-work-cover');if(t)t.textContent=updated.book.title||'Obra sem título';if(s)s.textContent=updated.book.subtitle||'Sem subtítulo';if(c){c.style.background=updated.book.color||'#7a3042';c.innerHTML=updated.book.coverUrl?'<img src="'+esc(updated.book.coverUrl)+'" alt="">':'<span>V</span>';}}
function sync(updated,preserveForm){live.workspace=updated;if(!preserveForm)live.form=initialForm(updated);syncHeader(updated);}
function clearTimer(){if(live.timer!==null){window.clearTimeout(live.timer);live.timer=null;}}
function scheduleSave(){clearTimer();live.dirty=true;live.saveState='saving';footer();live.timer=window.setTimeout(function(){live.timer=null;persist();},650);}
function persist(){clearTimer();if(!live.dirty)return Promise.resolve(live.workspace);if(live.savePromise)return live.savePromise;var version=live.editVersion,body=payload();live.busy=true;live.saveState='saving';footer();live.savePromise=api('/books/'+live.id+'/identification',{method:'PATCH',body:body}).then(function(w){var changed=live.editVersion!==version;sync(w,changed);live.busy=false;live.savePromise=null;if(changed){live.dirty=true;live.saveState='saving';refreshProgress();scheduleSave();}else{live.dirty=false;live.saveState='saved';refreshProgress();}return w;}).catch(function(e){live.busy=false;live.savePromise=null;live.saveState='error';live.dirty=true;footer();msg(e.message,true);throw e;});return live.savePromise;}
function navigateFoundation(){var u=new URL(location.href);u.searchParams.set('verbum_stage','project');history.pushState({},'',u);window.dispatchEvent(new Event('verbum:routechange'));}
function complete(){if(!ready()){msg('Preencha Título provisório, Gênero e Idioma para continuar.',true);return;}var afterSave=live.dirty||live.savePromise?persist():Promise.resolve(live.workspace);afterSave.then(function(w){var alreadyCompleted=!!(w&&w.identification&&w.identification.completed);var advanced=w&&w.currentStage&&w.currentStage!=='identification';if(alreadyCompleted||advanced){navigateFoundation();return;}live.busy=true;footer();api('/books/'+live.id+'/identification/complete',{method:'POST'}).then(function(updated){sync(updated,false);live.busy=false;navigateFoundation();}).catch(function(e){live.busy=false;live.saveState='error';footer();msg(e.message,true);});}).catch(function(){});}
function ensureSaved(){return live.dirty||live.savePromise?persist():Promise.resolve(live.workspace);}
function upload(file){if(!file)return;if(['image/jpeg','image/png','image/webp'].indexOf(file.type)<0){msg('Use uma imagem JPG, JPEG, PNG ou WebP.',true);return;}if(file.size>10485760){msg('A capa deve ter no máximo 10 MB.',true);return;}ensureSaved().then(function(){live.busy=true;footer();var d=new FormData();d.append('cover',file);return api('/books/'+live.id+'/cover',{method:'POST',body:d});}).then(function(w){live.busy=false;sync(w,false);mount(true);msg('Capa provisória atualizada.',false);}).catch(function(e){live.busy=false;footer();msg(e.message,true);});}
function removeCover(){if(!confirm('Remover a capa provisória desta obra?'))return;ensureSaved().then(function(){live.busy=true;footer();return api('/books/'+live.id+'/cover',{method:'DELETE'});}).then(function(w){live.busy=false;sync(w,false);mount(true);msg('Capa provisória removida.',false);}).catch(function(e){live.busy=false;footer();msg(e.message,true);});}
function editField(name,value){if(!Object.prototype.hasOwnProperty.call(live.form,name))return;live.form[name]=value;live.editVersion++;scheduleSave();refreshProgress();}
function bind(stage){var f=stage.querySelector('[data-id-form]');f.addEventListener('input',function(e){var n=e.target&&e.target.name;if(n)editField(n,e.target.value);});f.addEventListener('change',function(e){var n=e.target&&e.target.name;if(n)editField(n,e.target.value);});stage.querySelectorAll('[data-color]').forEach(function(b){b.onclick=function(){live.form.color=b.dataset.color||'';live.editVersion++;stage.querySelectorAll('[data-color]').forEach(function(x){x.classList.toggle('is-selected',x===b);});var preview=stage.querySelector('.verbum-cover-preview');if(preview)preview.style.background=live.form.color||'#15677a';scheduleSave();refreshProgress();};});var input=stage.querySelector('[data-cover-input]');stage.querySelectorAll('[data-cover-pick]').forEach(function(b){b.onclick=function(){if(!live.busy)input.click();};});input.onchange=function(){upload(input.files&&input.files[0]);};var drop=stage.querySelector('.verbum-cover-dropzone');if(drop){drop.ondragover=function(e){e.preventDefault();};drop.ondrop=function(e){e.preventDefault();upload(e.dataTransfer&&e.dataTransfer.files&&e.dataTransfer.files[0]);};}var rm=stage.querySelector('[data-cover-remove]');if(rm)rm.onclick=removeCover;}
function mount(force){var r=route(),stage=document.querySelector('.verbum-stage-content');if(!r.id||r.stage!=='identification'||!stage)return;if(!force&&stage.dataset.identificationMounted===r.id)return;function render(w){live.id=r.id;live.workspace=w;if(!live.dirty&&!live.savePromise)live.form=initialForm(w);stage.dataset.identificationMounted=r.id;stage.className='verbum-stage-content verbum-identification-stage';stage.innerHTML=pageHtml();bind(stage);refreshProgress();}var w=root.__vs&&root.__vs.workspace&&String(root.__vs.workspace.book.id)===String(r.id)?root.__vs.workspace:null;if(w)render(w);else api('/books/'+r.id+'/workspace').then(render).catch(function(e){msg(e.message,true);});}
window.addEventListener('beforeunload',function(e){if(live.dirty||live.savePromise){e.preventDefault();e.returnValue='';}});document.addEventListener('click',function(e){if(!live.dirty&&!live.savePromise)return;var t=e.target.closest&&e.target.closest('[data-stage],[data-close-work],[data-section],.verbum-work-back');if(t&&!confirm('Existem alterações sendo salvas. Deseja sair desta tela?')){e.preventDefault();e.stopImmediatePropagation();}},true);new MutationObserver(function(){mount(false);}).observe(document.body,{childList:true,subtree:true});window.addEventListener('verbum:routechange',function(){window.setTimeout(function(){mount(false);},0);});mount(false);
})();
