(function(){
'use strict';
var root=document.querySelector('[data-verbum-app]');if(!root)return;
var live={dirty:false,busy:false,workspace:null,form:null,id:null};
var status=['Planejamento','Em andamento','Em pausa'];
var genres=['Formação','Ensaio','Romance','Biografia','Devocional','Manual','Catequético','Acadêmico','Testemunho','Meditação','Não ficção','Ficção','Outro'];
var languages=['Português (BR)','Português (PT)','Espanhol','Inglês','Italiano','Francês','Outro'];
var audiences=['Leitores em geral','Crianças','Adolescentes','Jovens','Adultos','Famílias','Estudantes','Profissionais','Leigos','Clero e vida consagrada','Outro'];
var colors=['#15677a','#9b6b2f','#4f825e','#8b38d1','#c41f25','#244bb8','#bf1f62','#187a6f','#c84b0a','#4d3dc4'];
var labels=[['title','Definir título'],['subtitle','Definir subtítulo'],['synopsis','Escrever sinopse'],['keywords','Definir palavras-chave'],['workflowStatus','Definir status'],['genre','Definir gênero'],['language','Definir idioma'],['audience','Definir público-alvo'],['color','Escolher cor da obra'],['cover','Enviar capa da obra']];
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
function cfg(){return window.VerbumStudioConfig||{apiRoot:'/wp-json/verbum/v1',nonce:''};}
function api(path,opt){opt=opt||{};var c=cfg(),h={'X-WP-Nonce':c.nonce||''},body=opt.body,fd=typeof FormData!=='undefined'&&body instanceof FormData;if(body!==undefined&&!fd)h['Content-Type']='application/json';return fetch(c.apiRoot+path,{method:opt.method||'GET',credentials:'same-origin',headers:h,body:body===undefined?undefined:(fd?body:JSON.stringify(body))}).then(function(r){return r.json().then(function(p){if(!r.ok||!p.success)throw new Error(p&&p.error?p.error.message:'Erro na API.');return p.data;});});}
function route(){var p=new URLSearchParams(location.search);return{id:p.get('verbum_work'),stage:p.get('verbum_stage')||'identification'};}
function form(w){var b=w.book||{};return{title:b.title||'',subtitle:b.subtitle||'',workflowStatus:b.workflowStatus||'Planejamento',genre:b.genre||'',language:b.language==='Português'?'Português (BR)':(b.language||'Português (BR)'),audience:b.audience||'',synopsis:b.synopsis||'',keywords:Array.isArray(b.keywords)?b.keywords.join(', '):(b.keyword||''),color:b.color||''};}
function options(items,current){var a=items.slice();if(current&&a.indexOf(current)<0)a.unshift(current);return a.map(function(x){return'<option'+(x===current?' selected':'')+'>'+esc(x)+'</option>';}).join('');}
function checks(){var f=live.form,w=live.workspace,b=w&&w.book||{};var v={title:f.title.trim()!=='',subtitle:f.subtitle.trim()!=='',synopsis:f.synopsis.trim()!=='',keywords:f.keywords.split(',').some(function(x){return x.trim()!=='';}),workflowStatus:f.workflowStatus!=='',genre:f.genre!=='',language:f.language!=='',audience:f.audience!=='',color:f.color!=='',cover:!!b.coverUrl};return labels.map(function(x){return{key:x[0],label:x[1],completed:!!v[x[0]]};});}
function progressHtml(){var c=checks(),n=c.filter(function(x){return x.completed;}).length,p=n*10;return'<div class="verbum-progress-heading"><h3>Progresso da Etapa</h3><strong>'+p+'%</strong></div><div class="verbum-progress-track"><span style="width:'+p+'%"></span></div><p>'+n+' de 10 itens concluídos</p><div class="verbum-identification-checklist">'+c.map(function(x){return'<div class="'+(x.completed?'is-completed':'')+'"><span>'+(x.completed?'✓':'')+'</span><span>'+esc(x.label)+'</span></div>';}).join('')+'</div>';}
function pageHtml(){var f=live.form,b=live.workspace.book,cover=b.coverUrl||'';return'<div class="verbum-identification-layout"><form class="verbum-identification-card" data-id-form><div class="verbum-identification-grid">'+
'<label><span>Título</span><input name="title" value="'+esc(f.title)+'"></label><label><span>Subtítulo</span><input name="subtitle" value="'+esc(f.subtitle)+'"></label>'+
'<label><span>Status</span><select name="workflowStatus">'+options(status,f.workflowStatus)+'</select></label><label><span>Gênero</span><select name="genre"><option value="">Selecione...</option>'+options(genres,f.genre)+'</select></label>'+
'<label><span>Idioma</span><select name="language">'+options(languages,f.language)+'</select></label><label><span>Público-alvo</span><select name="audience"><option value="">Selecione...</option>'+options(audiences,f.audience)+'</select></label>'+
'<label class="verbum-identification-span-2"><span>Sinopse</span><textarea name="synopsis" rows="5">'+esc(f.synopsis)+'</textarea></label><label><span>Palavras-chave</span><input name="keywords" value="'+esc(f.keywords)+'"><small>Separe as palavras-chave por vírgula.</small></label>'+
'<div class="verbum-cover-field"><span class="verbum-field-label">Capa da obra</span><div class="verbum-cover-editor"><div class="verbum-cover-preview" style="background:'+esc(f.color||'#15677a')+'">'+(cover?'<img src="'+esc(cover)+'" alt="">':'<span>V</span>')+'</div><button type="button" class="verbum-cover-dropzone" data-cover-pick><strong>↻</strong><span>Arraste para substituir ou clique em “Trocar imagem”</span></button></div><div class="verbum-cover-actions"><button type="button" class="verbum-secondary-button" data-cover-pick>Trocar imagem</button><button type="button" class="verbum-text-button is-danger" data-cover-remove '+(!cover?'disabled':'')+'>Remover</button></div><input type="file" class="sr-only" accept="image/jpeg,image/png,image/webp" data-cover-input></div>'+
'<div class="verbum-identification-span-2 verbum-color-field"><span class="verbum-field-label">Cor da obra</span><div class="verbum-color-palette">'+colors.map(function(x){return'<button type="button" class="'+(f.color===x?'is-selected':'')+'" style="background:'+x+'" data-color="'+x+'"></button>';}).join('')+'</div></div></div><p class="verbum-identification-message" data-id-message hidden></p></form><aside class="verbum-identification-progress">'+progressHtml()+'</aside></div>';}
function payload(){var f=live.form;return{title:f.title.trim(),subtitle:f.subtitle.trim(),workflow_status:f.workflowStatus,genre:f.genre,language:f.language,audience:f.audience,synopsis:f.synopsis.trim(),keywords:f.keywords.split(',').map(function(x){return x.trim();}).filter(Boolean),color:f.color};}
function ready(){return checks().every(function(x){return x.completed;});}
function msg(text,error){var n=document.querySelector('[data-id-message]');if(!n)return;n.hidden=!text;n.textContent=text||'';n.classList.toggle('is-error',!!error);}
function footer(){var n=document.querySelector('.verbum-workspace-footer');if(!n)return;var done=!!(live.workspace.identification&&live.workspace.identification.completed&&!live.dirty);n.innerHTML='<button class="verbum-workspace-previous" disabled>‹ Etapa anterior</button><div class="verbum-workspace-save-actions"><span class="verbum-save-state" data-save-state>Salvo</span><button class="verbum-secondary-button" data-save '+(!live.dirty?'disabled':'')+'>Salvar</button><button class="verbum-primary-button" data-continue '+((!ready()||done)?'disabled':'')+'>'+(done?'Etapa concluída ✓':ready()?'Concluir etapa ›':'Salvar e continuar ›')+'</button></div>';n.querySelector('[data-save]').onclick=function(){save();};n.querySelector('[data-continue]').onclick=function(){complete();};}
function sync(updated){live.workspace=updated;live.form=form(updated);live.dirty=false;if(root.__vs){root.__vs.workspace=updated;if(root.__vs.library&&root.__vs.library.books)root.__vs.library.books=root.__vs.library.books.map(function(b){return b.id===updated.book.id?updated.book:b;});}var t=document.querySelector('.verbum-work-title h1'),s=document.querySelector('.verbum-work-title p'),c=document.querySelector('.verbum-work-cover');if(t)t.textContent=updated.book.title||'Obra sem título';if(s)s.textContent=updated.book.subtitle||'Sem subtítulo';if(c){c.style.background=updated.book.color||'#7a3042';c.innerHTML=updated.book.coverUrl?'<img src="'+esc(updated.book.coverUrl)+'" alt="">':'<span>V</span>';}}
function save(){if(live.busy)return;live.busy=true;api('/books/'+live.id+'/identification',{method:'PATCH',body:payload()}).then(function(w){sync(w);live.busy=false;mount(true);msg('Alterações salvas.',false);}).catch(function(e){live.busy=false;msg(e.message,true);});}
function complete(){if(live.dirty){save();setTimeout(complete,500);return;}if(!ready()){msg('Complete os itens pendentes da Identificação antes de continuar.',true);return;}live.busy=true;api('/books/'+live.id+'/identification/complete',{method:'POST'}).then(function(){var u=new URL(location.href);u.searchParams.set('verbum_stage','project');location.href=u.toString();}).catch(function(e){live.busy=false;msg(e.message,true);});}
function upload(file){if(!file)return;if(['image/jpeg','image/png','image/webp'].indexOf(file.type)<0){msg('Use uma imagem JPG, JPEG, PNG ou WebP.',true);return;}if(file.size>10485760){msg('A capa deve ter no máximo 10 MB.',true);return;}var d=new FormData();d.append('cover',file);api('/books/'+live.id+'/cover',{method:'POST',body:d}).then(function(w){sync(w);mount(true);msg('Capa atualizada.',false);}).catch(function(e){msg(e.message,true);});}
function bind(stage){var f=stage.querySelector('[data-id-form]');f.addEventListener('input',function(e){if(e.target.name){live.form[e.target.name]=e.target.value;live.dirty=true;stage.querySelector('.verbum-identification-progress').innerHTML=progressHtml();footer();}});f.addEventListener('change',function(e){if(e.target.name){live.form[e.target.name]=e.target.value;live.dirty=true;stage.querySelector('.verbum-identification-progress').innerHTML=progressHtml();footer();}});stage.querySelectorAll('[data-color]').forEach(function(b){b.onclick=function(){live.form.color=b.dataset.color;live.dirty=true;mount(true);};});var input=stage.querySelector('[data-cover-input]');stage.querySelectorAll('[data-cover-pick]').forEach(function(b){b.onclick=function(){input.click();};});input.onchange=function(){upload(input.files[0]);};var drop=stage.querySelector('.verbum-cover-dropzone');drop.ondragover=function(e){e.preventDefault();};drop.ondrop=function(e){e.preventDefault();upload(e.dataTransfer.files[0]);};var rm=stage.querySelector('[data-cover-remove]');if(rm)rm.onclick=function(){if(!confirm('Remover a capa desta obra?'))return;api('/books/'+live.id+'/cover',{method:'DELETE'}).then(function(w){sync(w);mount(true);msg('Capa removida.',false);}).catch(function(e){msg(e.message,true);});};}
function mount(force){var r=route(),stage=document.querySelector('.verbum-stage-content');if(!r.id||r.stage!=='identification'||!stage)return;if(!force&&stage.dataset.identificationMounted===r.id)return;function render(w){live.id=r.id;live.workspace=w;if(!live.dirty)live.form=form(w);stage.dataset.identificationMounted=r.id;stage.classList.add('verbum-identification-stage');stage.innerHTML=pageHtml();bind(stage);footer();}var w=root.__vs&&root.__vs.workspace&&root.__vs.workspace.book.id===r.id?root.__vs.workspace:null;if(w)render(w);else api('/books/'+r.id+'/workspace').then(render);}
window.addEventListener('beforeunload',function(e){if(live.dirty){e.preventDefault();e.returnValue='';}});document.addEventListener('click',function(e){if(!live.dirty)return;var t=e.target.closest&&e.target.closest('[data-stage],[data-close-work],[data-section],.verbum-work-back');if(t&&!confirm('Existem alterações que ainda não foram salvas. Sair sem salvar?')){e.preventDefault();e.stopImmediatePropagation();}},true);new MutationObserver(function(){mount(false);}).observe(document.body,{childList:true,subtree:true});mount(false);
})();
