(function(){
'use strict';
var root=document.querySelector('[data-verbum-app]');if(!root)return;
var stageLabels={identification:'Identificação',project:'Projeto da Obra',planning:'Planejamento',development:'Desenvolvimento',general_review:'Revisão Geral',versions:'Controle de Versões',audit:'Auditoria',editorial_desk:'Mesa Editorial',layout:'Diagramação',legal:'Trâmites Legais',publication:'Publicação'};
function bookForCard(card){var state=root.__vs,books=state&&state.library&&state.library.books||[],title=card.querySelector('h3');if(!title)return null;return books.find(function(book){return String(book.title||'')===title.textContent.trim();})||null;}
function setText(node,text){if(node&&node.textContent!==text)node.textContent=text;}
function simplifyBookDialog(){var form=root.querySelector('[data-book-form]');if(!form||form.dataset.technicalSimplified==='1')return;form.dataset.technicalSimplified='1';var grid=form.querySelector('.verbum-form-grid');if(!grid)return;var project=grid.querySelector('[name="project_id"]'),projectLabel=project&&project.closest('label');if(projectLabel){var internalProject=document.createElement('input');internalProject.type='hidden';internalProject.name='project_id';internalProject.value=project.value;form.appendChild(internalProject);projectLabel.remove();}var allowed=['title','subtitle'];grid.querySelectorAll('label').forEach(function(label){var field=label.querySelector('[name]');if(field&&allowed.indexOf(field.name)<0)label.remove();});var note=document.createElement('p');note.className='verbum-form-helper';note.textContent='Cadastre apenas os dados iniciais. A identificação editorial completa será preenchida dentro do ambiente da obra.';grid.insertAdjacentElement('afterend',note);var dialog=form.closest('.verbum-dialog'),eyebrow=dialog&&dialog.querySelector('.verbum-eyebrow');setText(eyebrow,'Banco de Obras');}
function clarifyBookCards(){root.querySelectorAll('.verbum-book-card').forEach(function(card){var book=bookForCard(card);if(!book)return;var chip=card.querySelector('.verbum-status-chip');if(chip&&book.status!=='archived')setText(chip,'Situação: '+(book.workflowStatus||'Planejamento'));var stage=card.querySelector('.verbum-book-stage strong');setText(stage,stageLabels[book.stage]||'Identificação');});}
function hideIdentificationPrevious(){var params=new URLSearchParams(location.search),stage=params.get('verbum_stage')||'identification';if(stage!=='identification')return;var previous=root.querySelector('.verbum-workspace-previous');if(previous&&previous.disabled&&!previous.hidden){previous.hidden=true;previous.setAttribute('aria-hidden','true');var footer=previous.closest('.verbum-workspace-footer');if(footer)footer.classList.add('is-first-stage');}}
function localDate(value){if(!value)return '—';var normalized=/Z$|[+-]\d\d:\d\d$/.test(value)?value:value+'Z';var date=new Date(normalized);if(Number.isNaN(date.getTime()))return '—';var today=new Date();var dateDay=new Date(date.getFullYear(),date.getMonth(),date.getDate());var todayDay=new Date(today.getFullYear(),today.getMonth(),today.getDate());var diff=Math.round((todayDay-dateDay)/86400000);if(diff===0)return'hoje';if(diff===1)return'ontem';return date.toLocaleDateString('pt-BR',{day:'2-digit',month:'2-digit'});}
function fixLastEdited(){var state=root.__vs,w=state&&state.workspace;if(!w||!w.metrics)return;root.querySelectorAll('.verbum-work-metrics>div').forEach(function(item){var label=item.querySelector('span'),value=item.querySelector('strong');if(label&&value&&label.textContent.trim()==='ÚLTIMA EDIÇÃO')setText(value,localDate(w.metrics.lastEdited));});}
function apply(){simplifyBookDialog();clarifyBookCards();hideIdentificationPrevious();fixLastEdited();}
new MutationObserver(apply).observe(root,{childList:true,subtree:true});window.addEventListener('popstate',function(){setTimeout(apply,0);});apply();
})();
