import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

const root = resolve(new URL('../', import.meta.url).pathname);
const repoRoot = resolve(root, '../..');
const requiredFiles = [
  'src/services/api-client.ts','src/services/core-service.ts','src/services/library-service.ts','src/services/work-versions-service.ts','src/services/work-audit-service.ts','src/types/general-review.ts','src/types/work-versions.ts','src/types/work-audit.ts',
  'src/components/AppShell.tsx','src/components/Sidebar.tsx','src/components/Header.tsx','src/components/UserMenu.tsx',
  'src/components/ProjectDialog.tsx','src/components/BookDialog.tsx','src/components/BookCard.tsx',
  'src/components/WorkHeader.tsx','src/components/WorkWorkflow.tsx','src/components/WorkspaceFooter.tsx','src/components/IdentificationStage.tsx','src/components/ProjectStage.tsx','src/components/PlanningStage.tsx','src/components/DevelopmentStage.tsx','src/components/ChapterPreparationStage.tsx','src/components/ChapterResearchStage.tsx','src/components/ChapterWritingStage.tsx','src/components/ChapterRevisionStage.tsx','src/components/GeneralReviewStage.tsx','src/components/WorkVersionsStage.tsx','src/components/WorkAuditStage.tsx',
  'src/pages/Dashboard.tsx','src/pages/LibraryPage.tsx','src/pages/WorkWorkspace.tsx','src/main.tsx','src/pages/VerbumApp.tsx',
  'src/styles/verbum.css','src/styles/library.css','src/styles/workspace.css','src/styles/identification.css','src/styles/project-stage.css','src/styles/planning-stage.css','src/styles/development-stage.css','src/styles/chapter-preparation.css','src/styles/chapter-research.css','src/styles/chapter-writing.css','src/styles/chapter-revision.css','src/styles/general-review.css','src/styles/work-versions.css','src/styles/work-audit.css','src/styles/chapter-workflow.css','src/styles/technical.css','src/styles/dashboard-official.css','src/styles/minhas-obras.css','src/styles/auth-profile.css','src/styles/profile-polish.css',
  'src/auth-profile-runtime.js','src/static-runtime.js','src/workspace-mobile-runtime.js','src/identification-runtime.js','src/project-stage-runtime.js','src/planning-stage-runtime.js','src/development-stage-runtime.js','src/chapter-workflow-runtime.js','src/chapter-preparation-runtime.js','src/chapter-research-runtime.js','src/chapter-writing-runtime.js','src/chapter-revision-runtime.js','src/general-review-runtime.js','src/work-versions-runtime.js','src/work-audit-runtime.js','src/technical-runtime.js','src/dashboard-official-runtime.js','src/sidebar-profile-runtime.js','src/minhas-obras-runtime.js','src/profile-polish-runtime.js','src/vite-env.d.ts',
];
for (const file of requiredFiles) { const contents = await readFile(resolve(root, file), 'utf8'); if (!contents.trim()) throw new Error(`${file} is empty`); }
function requireAll(contents, expected, label) { for (const item of expected) if (!contents.includes(item)) throw new Error(`${label} missing: ${item}`); }
const app = await readFile(resolve(root, 'src/pages/VerbumApp.tsx'), 'utf8'); requireAll(app, ['getHealth()','getCurrentUser()','getLibrary()','getWorkWorkspace','<WorkWorkspace','<WorkHeader','hideHeader'], 'VerbumApp');
const header = await readFile(resolve(root, 'src/components/Header.tsx'), 'utf8'); if (header.includes('Área atual')) throw new Error('Header must not render Área atual');
const sidebar = await readFile(resolve(root, 'src/components/Sidebar.tsx'), 'utf8'); if (!sidebar.includes('Minhas Obras')) throw new Error('Sidebar must use Minhas Obras');
const workspace = await readFile(resolve(root, 'src/pages/WorkWorkspace.tsx'), 'utf8'); requireAll(workspace, ['IdentificationStage','ProjectStage','PlanningStage','DevelopmentStage','GeneralReviewStage','WorkVersionsStage','WorkAuditStage','WorkWorkflow','WorkspaceFooter','beforeunload'], 'WorkWorkspace');
const development = await readFile(resolve(root, 'src/components/DevelopmentStage.tsx'), 'utf8'); requireAll(development, ['Desenvolvimento da Obra','ChapterPreparationStage','ChapterResearchStage','ChapterWritingStage','ChapterRevisionStage','chapterViewStage','Preparação','Pesquisa','Redação','Revisão','Abrir capítulo'], 'DevelopmentStage');
const preparation = await readFile(resolve(root, 'src/components/ChapterPreparationStage.tsx'), 'utf8'); requireAll(preparation, ['Identidade do Capítulo','Direção da Escrita','Estrutura Inicial','Fontes que deverão ser pesquisadas','Intenção Espiritual do Capítulo','Concluir Preparação','completeChapterPreparation'], 'ChapterPreparationStage');
const research = await readFile(resolve(root, 'src/components/ChapterResearchStage.tsx'), 'utf8'); requireAll(research, ['Direção da Pesquisa','Central de Pesquisa','Banco de Ideias do capítulo','Selecionados para Redação','Concluir Pesquisa','completeChapterResearch','createChapterResearchSource'], 'ChapterResearchStage');
const writing = await readFile(resolve(root, 'src/components/ChapterWritingStage.tsx'), 'utf8'); requireAll(writing, ['Assistente de Escrita','Modo Foco','Salvar agora','Introdução','Desenvolvimento','Conclusão','Inserir na Redação','Histórico de versões','Concluir Redação','assistChapterWriting','completeChapterWriting'], 'ChapterWritingStage');
const revision = await readFile(resolve(root, 'src/components/ChapterRevisionStage.tsx'), 'utf8'); requireAll(revision, ['Direção original','Estrutura planejada × escrita','Fontes e Citações','Pendências da Revisão','Assistente de Revisão','Concluir Revisão','alteredAfterCompletion','assistChapterRevision','completeChapterRevision'], 'ChapterRevisionStage');
const generalReview = await readFile(resolve(root, 'src/components/GeneralReviewStage.tsx'), 'utf8'); requireAll(generalReview, ['Revisão Geral da Obra','Ler obra completa','Direção Original da Obra','Transições entre capítulos','Terminologia da obra','Pendências da Revisão Geral','Assistente de Revisão Geral','Concluir Revisão Geral','completeGeneralReview','getGeneralReviewReading'], 'GeneralReviewStage');
const versionsStage = await readFile(resolve(root, 'src/components/WorkVersionsStage.tsx'), 'utf8'); requireAll(versionsStage, ['Controle de Versões','Alterações não versionadas','Histórico da Obra','Comparar versões','Versão para Auditoria','Restaurar esta versão','Concluir Controle de Versões','createWorkVersion','restoreWorkVersion','compareWorkVersions','completeWorkVersions'], 'WorkVersionsStage');
const auditStage = await readFile(resolve(root, 'src/components/WorkAuditStage.tsx'), 'utf8'); requireAll(auditStage, ['Auditoria da Obra','Versão em Auditoria','Achados da Auditoria','Elementos editoriais','Fontes e Referências','Relatório de Auditoria','Assistente de Auditoria','Histórico de rodadas','Aprovar Auditoria','completeWorkAudit','generateAuditReport'], 'WorkAuditStage');
const preparationRuntime = await readFile(resolve(root, 'src/chapter-preparation-runtime.js'), 'utf8'); requireAll(preparationRuntime, ['/preparation','/preparation/complete','Concluir Preparação','source_categories'], 'Chapter preparation runtime');
const researchRuntime = await readFile(resolve(root, 'src/chapter-research-runtime.js'), 'utf8'); requireAll(researchRuntime, ['/research','/research/sources','/research/complete','Direção da Pesquisa','Central de Pesquisa','Banco de Ideias do capítulo','Concluir Pesquisa','selected_for_writing'], 'Chapter research runtime');
const writingRuntime = await readFile(resolve(root, 'src/chapter-writing-runtime.js'), 'utf8'); requireAll(writingRuntime, ['/writing','/writing/complete','/writing/assist','Assistente de Escrita','Modo Foco','Salvar agora','Concluir Redação','data-writing-editor'], 'Chapter writing runtime');
const revisionRuntime = await readFile(resolve(root, 'src/chapter-revision-runtime.js'), 'utf8'); requireAll(revisionRuntime, ['/revision','/revision/issues','/revision/complete','/revision/assist','Pendências da Revisão','Assistente de Revisão','Concluir Revisão','data-revision-editor'], 'Chapter revision runtime');
const generalRuntime = await readFile(resolve(root, 'src/general-review-runtime.js'), 'utf8'); requireAll(generalRuntime, ['/general-review','/general-review/reading','/general-review/issues','/general-review/complete','/general-review/assist','Revisão Geral da Obra','Ler obra completa','Pendências da Revisão Geral','Assistente de Revisão Geral'], 'General review runtime');
const versionsRuntime = await readFile(resolve(root, 'src/work-versions-runtime.js'), 'utf8'); requireAll(versionsRuntime, ['/versions-stage','/versions-stage/versions','/versions-stage/compare','/audit-baseline','/restore','Controle de Versões','Alterações não versionadas','Histórico da Obra','Concluir Controle de Versões'], 'Work versions runtime');
const auditRuntime = await readFile(resolve(root, 'src/work-audit-runtime.js'), 'utf8'); requireAll(auditRuntime, ['/audit-stage','/audit-stage/findings','/audit-stage/report','/audit-stage/assist','/audit-stage/complete','Auditoria da Obra','Versão em Auditoria','Achados da Auditoria','Relatório de Auditoria','Assistente de Auditoria','Aprovar Auditoria'], 'Work audit runtime');
const workflowRuntime = await readFile(resolve(root, 'src/chapter-workflow-runtime.js'), 'utf8'); requireAll(workflowRuntime, ['verbum_chapter_stage','Preparação','Pesquisa','Redação','Revisão','verbum-chapter-revision-host','is-selected'], 'Chapter workflow runtime');
const preparationCss = await readFile(resolve(root, 'src/styles/chapter-preparation.css'), 'utf8'); requireAll(preparationCss, ['.verbum-preparation-layout','.verbum-preparation-card','.verbum-preparation-progress','.verbum-preparation-sources','@media'], 'Chapter preparation CSS');
const researchCss = await readFile(resolve(root, 'src/styles/chapter-research.css'), 'utf8'); requireAll(researchCss, ['.verbum-research-layout','.verbum-research-direction','.verbum-research-source-card','.verbum-research-progress','.verbum-research-ideas','@media'], 'Chapter research CSS');
const writingCss = await readFile(resolve(root, 'src/styles/chapter-writing.css'), 'utf8'); requireAll(writingCss, ['.verbum-writing-layout','.verbum-writing-paper','.verbum-writing-toolbar','.verbum-writing-research','.verbum-writing-progress','verbum-writing-focus-mode','@media'], 'Chapter writing CSS');
const revisionCss = await readFile(resolve(root, 'src/styles/chapter-revision.css'), 'utf8'); requireAll(revisionCss, ['.verbum-revision-layout','.verbum-revision-paper','.verbum-revision-checklist','.verbum-revision-sources','.verbum-revision-issues','.verbum-revision-assistant','@media'], 'Chapter revision CSS');
const generalCss = await readFile(resolve(root, 'src/styles/general-review.css'), 'utf8'); requireAll(generalCss, ['.verbum-general-review-layout','.verbum-general-review-direction','.verbum-general-review-transitions','.verbum-general-review-reading','.verbum-general-review-issues','.verbum-general-review-assistant','@media'], 'General review CSS');
const versionsCss = await readFile(resolve(root, 'src/styles/work-versions.css'), 'utf8'); requireAll(versionsCss, ['.verbum-versions-layout','.verbum-version-card','.verbum-versions-progress-card','.verbum-versions-compare-panel','.verbum-version-reader','.verbum-versions-modal-backdrop','@media'], 'Work versions CSS');
const auditCss = await readFile(resolve(root, 'src/styles/work-audit.css'), 'utf8'); requireAll(auditCss, ['.verbum-audit-layout','.verbum-audit-card','.verbum-audit-findings','.verbum-audit-progress','.verbum-audit-assistant','.verbum-audit-elements','.verbum-audit-sources','@media'], 'Work audit CSS');
const libraryService = await readFile(resolve(root, 'src/services/library-service.ts'), 'utf8'); requireAll(libraryService, ['getChapterResearch','completeChapterResearch','getChapterWriting','saveChapterWriting','completeChapterWriting','assistChapterWriting','getChapterRevision','saveChapterRevision','createChapterRevisionIssue','completeChapterRevision','assistChapterRevision','getGeneralReview','saveGeneralReview','getGeneralReviewReading','createGeneralReviewIssue','completeGeneralReview','assistGeneralReview'], 'Library service');
const versionsService = await readFile(resolve(root, 'src/services/work-versions-service.ts'), 'utf8'); requireAll(versionsService, ['getWorkVersions','createWorkVersion','getWorkVersion','compareWorkVersions','restoreWorkVersion','selectAuditWorkVersion','completeWorkVersions'], 'Work versions service');
const auditService = await readFile(resolve(root, 'src/services/work-audit-service.ts'), 'utf8'); requireAll(auditService, ['getWorkAudit','saveWorkAuditState','createAuditFinding','updateAuditFinding','generateAuditReport','assistWorkAudit','completeWorkAudit'], 'Work audit service');
const authRuntime = await readFile(resolve(root, 'src/auth-profile-runtime.js'), 'utf8'); requireAll(authRuntime, ['/auth/login','/auth/register','/profile','Minha conta','Trocar foto'], 'Auth/profile runtime');
const buildJs = await readFile(resolve(repoRoot, 'build/verbum-app.js'), 'utf8'); requireAll(buildJs, ['development-stage-runtime.js','chapter-workflow-runtime.js','chapter-preparation-runtime.js','chapter-research-runtime.js','chapter-writing-runtime.js','chapter-revision-runtime.js','general-review-runtime.js','work-versions-runtime.js','work-audit-runtime.js','script.async=false'], 'Static JS build');
const buildCss = await readFile(resolve(repoRoot, 'build/verbum-app.css'), 'utf8'); requireAll(buildCss, ['development-stage.css','chapter-preparation.css','chapter-research.css','chapter-writing.css','chapter-revision.css','general-review.css','work-versions.css','work-audit.css','chapter-workflow.css','profile-polish.css'], 'Static CSS build');
const sensitivePattern = /(SUPABASE_SERVICE|SERVICE_KEY|OPENAI_API_KEY|sk-[A-Za-z0-9_-]{10,})/;
for (const file of requiredFiles) { const contents = await readFile(resolve(root, file), 'utf8'); if (sensitivePattern.test(contents)) throw new Error(`Sensitive value pattern found in ${file}`); }
console.log('Frontend Sprint 15 Auditoria da Obra checks passed');
