<?php

declare(strict_types=1);

namespace VerbumStudio\Api;

use VerbumStudio\Auth\Capabilities;use VerbumStudio\Core\Config;use VerbumStudio\Exceptions\ValidationError;use VerbumStudio\Library\LibraryRepository;use VerbumStudio\Library\StructureElementsRepository;

final class StructureElementsController
{
    private Config$config;private ResponseFactory$responses;private Capabilities$capabilities;private LibraryRepository$library;private StructureElementsRepository$elements;
    public function __construct(Config$c,ResponseFactory$r,Capabilities$a,LibraryRepository$l,StructureElementsRepository$e){$this->config=$c;$this->responses=$r;$this->capabilities=$a;$this->library=$l;$this->elements=$e;}
    public function register():void{add_action('rest_api_init',function():void{$n=$this->config->get('api_namespace');$p=[$this,'canAccess'];$b='/books/(?P<id>\d+)/structure/elements';register_rest_route($n,$b,[['methods'=>'GET','callback'=>[$this,'show'],'permission_callback'=>$p],['methods'=>'PATCH','callback'=>[$this,'save'],'permission_callback'=>$p]]);register_rest_route($n,$b.'/complete',['methods'=>'POST','callback'=>[$this,'complete'],'permission_callback'=>$p]);register_rest_route($n,$b.'/analyze',['methods'=>'POST','callback'=>[$this,'analyze'],'permission_callback'=>$p]);});}public function canAccess():bool{return$this->capabilities->currentUserCanAccess();}private function owned(int$id):void{$this->library->workspaceForBook(get_current_user_id(),$id);}public function show(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->elements->data($id));}catch(\Throwable$e){return$this->responses->error($e);}}public function save(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();return$this->responses->success($this->elements->save($id,is_array($p)?$p:[]));}catch(\Throwable$e){return$this->responses->error($e);}}public function complete(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->elements->complete($id));}catch(\Throwable$e){return$this->responses->error($e);}}
    public function analyze(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();$j=$this->ai('Analise os elementos editoriais sem alterar dados. Considere ordem, duplicações, ausências possíveis, classificação, Carta aos Leitores e itens desativados. Não trate nenhum elemento como universalmente obrigatório. Responda JSON com adequate, missing, duplicates, order_suggestions e alerts; cada item contém observation, impact e element_id opcional.',wp_json_encode(['context'=>$this->elements->data($id),'draft'=>is_array($p)?$p:[]],JSON_UNESCAPED_UNICODE));$o=[];foreach(['adequate','missing','duplicates','order_suggestions','alerts']as$k)$o[$this->camel($k)]=$this->observations($j[$k]??[]);return$this->responses->success($o);}catch(\Throwable$e){return$this->responses->error($e);}}
    /** @return array<string,mixed> */ private function ai(string$i,string$input):array{$key=trim((string)$this->config->get('openai_api_key',''));if($key==='')throw new ValidationError('A assistência editorial está indisponível porque VERBUM_OPENAI_API_KEY ainda não foi configurada no servidor.');$res=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>60,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>'gpt-5.6-luna','instructions'=>$i,'input'=>$input,'max_output_tokens'=>2600])]);if(is_wp_error($res)||(int)wp_remote_retrieve_response_code($res)<200||(int)wp_remote_retrieve_response_code($res)>=300)throw new ValidationError('A inteligência artificial não conseguiu concluir a análise.');$b=json_decode((string)wp_remote_retrieve_body($res),true);$text='';foreach((array)($b['output']??[])as$x)foreach((array)($x['content']??[])as$c)if(($c['type']??'')==='output_text')$text.=(string)($c['text']??'');if(preg_match('/^```(?:json)?\s*(.*?)\s*```$/s',trim($text),$m))$text=$m[1];$j=json_decode(trim($text),true);if(!is_array($j))throw new ValidationError('A inteligência artificial retornou uma resposta inválida.');return$j;}private function camel(string$v):string{return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$v))));}/** @param mixed$x @return array<int,array<string,string>> */private function observations($x):array{$o=[];foreach(is_array($x)?$x:[]as$v)if(is_array($v)&&trim((string)($v['observation']??''))!=='')$o[]=['observation'=>sanitize_textarea_field((string)$v['observation']),'impact'=>sanitize_textarea_field((string)($v['impact']??'')),'elementId'=>sanitize_key((string)($v['element_id']??''))];return$o;}
}
