<?php

declare(strict_types=1);

namespace VerbumStudio\Api;

use VerbumStudio\Auth\Capabilities;use VerbumStudio\Core\Config;use VerbumStudio\Exceptions\ValidationError;use VerbumStudio\Library\LibraryRepository;use VerbumStudio\Library\StructureArchitectureRepository;

final class StructureArchitectureController
{
    private Config$config;private ResponseFactory$responses;private Capabilities$capabilities;private LibraryRepository$library;private StructureArchitectureRepository$architecture;
    public function __construct(Config$c,ResponseFactory$r,Capabilities$a,LibraryRepository$l,StructureArchitectureRepository$x){$this->config=$c;$this->responses=$r;$this->capabilities=$a;$this->library=$l;$this->architecture=$x;}
    public function register():void{add_action('rest_api_init',function():void{$n=$this->config->get('api_namespace');$p=[$this,'canAccess'];$b='/books/(?P<id>\d+)/structure/architecture';register_rest_route($n,$b,[['methods'=>'GET','callback'=>[$this,'show'],'permission_callback'=>$p],['methods'=>'PATCH','callback'=>[$this,'save'],'permission_callback'=>$p]]);register_rest_route($n,$b.'/complete',['methods'=>'POST','callback'=>[$this,'complete'],'permission_callback'=>$p]);register_rest_route($n,$b.'/generate',['methods'=>'POST','callback'=>[$this,'generate'],'permission_callback'=>$p]);register_rest_route($n,$b.'/analyze',['methods'=>'POST','callback'=>[$this,'analyze'],'permission_callback'=>$p]);});}
    public function canAccess():bool{return$this->capabilities->currentUserCanAccess();}private function owned(int$id):void{$this->library->workspaceForBook(get_current_user_id(),$id);}public function show(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->architecture->data($id));}catch(\Throwable$e){return$this->responses->error($e);}}public function save(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();return$this->responses->success($this->architecture->save($id,is_array($p)?$p:[]));}catch(\Throwable$e){return$this->responses->error($e);}}public function complete(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->architecture->complete($id));}catch(\Throwable$e){return$this->responses->error($e);}}
    public function generate(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$d=$this->architecture->data($id);$j=$this->ai('Proponha uma arquitetura não destrutiva em partes para esta obra. Responda somente JSON com overview, rationale e parts. Cada parte: title, function, theme, expected_result, entry_transition, next_transition, movement_id, estimated_chapters, justification. Use somente movement_id existentes. Não crie capítulos.',wp_json_encode($d,JSON_UNESCAPED_UNICODE),3600);return$this->responses->success(['overview'=>sanitize_textarea_field((string)($j['overview']??'')),'rationale'=>sanitize_textarea_field((string)($j['rationale']??'')),'parts'=>$this->suggestions($j['parts']??[],$d)]);}catch(\Throwable$e){return$this->responses->error($e);}}
    public function analyze(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();$j=$this->ai('Analise sem alterar dados: progressão, movimentos, ordem teológica, repetições, lacunas, uniões, divisões, reordenação, transições, começo, chegada e limites. Responda JSON com coherent_points, gaps, repetitions, merges, splits, reorder, alerts. Cada item deve conter observation e impact.',wp_json_encode(['context'=>$this->architecture->data($id),'draft'=>is_array($p)?$p:[]],JSON_UNESCAPED_UNICODE),3200);$o=[];foreach(['coherent_points','gaps','repetitions','merges','splits','reorder','alerts']as$k)$o[$this->camel($k)]=$this->observations($j[$k]??[]);return$this->responses->success($o);}catch(\Throwable$e){return$this->responses->error($e);}}
    /** @return array<string,mixed> */ private function ai(string$i,string$input,int$max):array{$key=trim((string)$this->config->get('openai_api_key',''));if($key==='')throw new ValidationError('A assistência de arquitetura está indisponível porque VERBUM_OPENAI_API_KEY ainda não foi configurada no servidor.');$res=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>60,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>'gpt-5.6-luna','instructions'=>$i,'input'=>$input,'max_output_tokens'=>$max])]);if(is_wp_error($res)||(int)wp_remote_retrieve_response_code($res)<200||(int)wp_remote_retrieve_response_code($res)>=300)throw new ValidationError('A inteligência artificial não conseguiu concluir a solicitação. Tente novamente.');$b=json_decode((string)wp_remote_retrieve_body($res),true);$text='';foreach((array)($b['output']??[])as$x)foreach((array)($x['content']??[])as$c)if(($c['type']??'')==='output_text')$text.=(string)($c['text']??'');if(preg_match('/^```(?:json)?\s*(.*?)\s*```$/s',trim($text),$m))$text=$m[1];$j=json_decode(trim($text),true);if(!is_array($j))throw new ValidationError('A inteligência artificial retornou uma resposta inválida.');return$j;}
    /** @param mixed $items @param array<string,mixed>$d @return array<int,array<string,mixed>> */ private function suggestions($items,array$d):array{$valid=[];foreach((array)$d['direction']['movement']as$m)$valid[]=(string)($m['id']??'');$o=[];foreach(is_array($items)?$items:[]as$x){if(!is_array($x))continue;$title=trim(sanitize_text_field((string)($x['title']??'')));$mid=sanitize_key((string)($x['movement_id']??''));if($title===''||!in_array($mid,$valid,true))continue;$o[]=['title'=>$title,'function'=>sanitize_textarea_field((string)($x['function']??'')),'theme'=>sanitize_textarea_field((string)($x['theme']??'')),'expectedResult'=>sanitize_textarea_field((string)($x['expected_result']??'')),'entryTransition'=>sanitize_textarea_field((string)($x['entry_transition']??'')),'nextTransition'=>sanitize_textarea_field((string)($x['next_transition']??'')),'movementId'=>$mid,'estimatedChapters'=>max(0,(int)($x['estimated_chapters']??0)),'justification'=>sanitize_textarea_field((string)($x['justification']??''))];}return$o;}
    /** @param mixed$items @return array<int,array<string,string>> */ private function observations($items):array{$o=[];foreach(is_array($items)?$items:[]as$x){if(is_string($x))$o[]=['observation'=>sanitize_textarea_field($x),'impact'=>''];elseif(is_array($x)&&trim((string)($x['observation']??''))!=='')$o[]=['observation'=>sanitize_textarea_field((string)$x['observation']),'impact'=>sanitize_textarea_field((string)($x['impact']??''))];}return$o;}private function camel(string$v):string{return lcfirst(str_replace(' ','',ucwords(str_replace('_',' ',$v))));}
}
