<?php

declare(strict_types=1);

namespace VerbumStudio\Api;

use VerbumStudio\Auth\Capabilities;use VerbumStudio\Core\Config;use VerbumStudio\Exceptions\ValidationError;use VerbumStudio\Library\LibraryRepository;use VerbumStudio\Library\StructureIndexRepository;

final class StructureIndexController
{
    private Config$config;private ResponseFactory$responses;private Capabilities$capabilities;private LibraryRepository$library;private StructureIndexRepository$index;
    public function __construct(Config$c,ResponseFactory$r,Capabilities$a,LibraryRepository$l,StructureIndexRepository$i){$this->config=$c;$this->responses=$r;$this->capabilities=$a;$this->library=$l;$this->index=$i;}public function register():void{add_action('rest_api_init',function():void{$n=$this->config->get('api_namespace');$p=[$this,'canAccess'];$b='/books/(?P<id>\d+)/structure/index';register_rest_route($n,$b,[['methods'=>'GET','callback'=>[$this,'show'],'permission_callback'=>$p],['methods'=>'PATCH','callback'=>[$this,'save'],'permission_callback'=>$p]]);register_rest_route($n,$b.'/complete',['methods'=>'POST','callback'=>[$this,'complete'],'permission_callback'=>$p]);register_rest_route($n,$b.'/generate',['methods'=>'POST','callback'=>[$this,'generate'],'permission_callback'=>$p]);register_rest_route($n,$b.'/analyze',['methods'=>'POST','callback'=>[$this,'analyze'],'permission_callback'=>$p]);});}public function canAccess():bool{return$this->capabilities->currentUserCanAccess();}private function owned(int$id):void{$this->library->workspaceForBook(get_current_user_id(),$id);}public function show(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->index->data($id));}catch(\Throwable$e){return$this->responses->error($e);}}public function save(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();return$this->responses->success($this->index->save($id,is_array($p)?$p:[]));}catch(\Throwable$e){return$this->responses->error($e);}}public function complete(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->index->complete($id));}catch(\Throwable$e){return$this->responses->error($e);}}
    public function generate(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$d=$this->index->data($id);$j=$this->ai('Sugira somente itens provisórios de índice para as Partes fornecidas. Não crie capítulos reais. Responda JSON com overview e items. Cada item contém type chapter ou subchapter, title, parent_id, purpose, thesis_contribution, expected_result, movement_id e justification. parent_id deve corresponder a um ID existente ou a outro item sugerido.',wp_json_encode($d,JSON_UNESCAPED_UNICODE),3600);return$this->responses->success(['overview'=>sanitize_textarea_field((string)($j['overview']??'')),'items'=>$this->generated($j['items']??[])]);}catch(\Throwable$e){return$this->responses->error($e);}}
    public function analyze(\WP_REST_Request$r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$r->get_json_params();$j=$this->ai('Analise o índice sem modificar dados. Verifique tese, objetivos, progressão, repetições, lacunas, amplitude, uniões, divisões, limites, subcapítulos e equilíbrio. Responda JSON com suggestions. Cada sugestão contém item_id, observation e impact.',wp_json_encode(['context'=>$this->index->data($id),'draft'=>is_array($p)?$p:[]],JSON_UNESCAPED_UNICODE),2600);$out=[];foreach((array)($j['suggestions']??[])as$i=>$x)if(is_array($x)&&trim((string)($x['observation']??''))!=='')$out[]=['id'=>'review-'.substr(md5(wp_json_encode($x).'|'.$i),0,10),'itemId'=>sanitize_key((string)($x['item_id']??'')),'observation'=>sanitize_textarea_field((string)$x['observation']),'impact'=>sanitize_textarea_field((string)($x['impact']??'')),'status'=>'pending'];return$this->responses->success(['suggestions'=>$out]);}catch(\Throwable$e){return$this->responses->error($e);}}
    /** @return array<string,mixed> */private function ai(string$i,string$input,int$max):array{$key=trim((string)$this->config->get('openai_api_key',''));if($key==='')throw new ValidationError('A revisão do índice está indisponível porque VERBUM_OPENAI_API_KEY ainda não foi configurada no servidor.');$res=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>60,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>'gpt-5.6-luna','instructions'=>$i,'input'=>$input,'max_output_tokens'=>$max])]);if(is_wp_error($res)||(int)wp_remote_retrieve_response_code($res)<200||(int)wp_remote_retrieve_response_code($res)>=300)throw new ValidationError('A inteligência artificial não conseguiu concluir a solicitação.');$b=json_decode((string)wp_remote_retrieve_body($res),true);$text='';foreach((array)($b['output']??[])as$x)foreach((array)($x['content']??[])as$c)if(($c['type']??'')==='output_text')$text.=(string)($c['text']??'');if(preg_match('/^```(?:json)?\s*(.*?)\s*```$/s',trim($text),$m))$text=$m[1];$j=json_decode(trim($text),true);if(!is_array($j))throw new ValidationError('A inteligência artificial retornou uma resposta inválida.');return$j;}/** @param mixed$x @return array<int,array<string,mixed>> */private function generated($x):array{$o=[];foreach(is_array($x)?$x:[]as$i=>$v){if(!is_array($v))continue;$type=($v['type']??'chapter')==='subchapter'?'subchapter':'chapter';$title=trim(sanitize_text_field((string)($v['title']??'')));if($title==='')continue;$o[]=['suggestionId'=>'suggestion-'.substr(md5(wp_json_encode($v).'|'.$i),0,10),'type'=>$type,'title'=>$title,'parentId'=>sanitize_key((string)($v['parent_id']??'')),'purpose'=>sanitize_textarea_field((string)($v['purpose']??'')),'thesisContribution'=>sanitize_textarea_field((string)($v['thesis_contribution']??'')),'expectedResult'=>sanitize_textarea_field((string)($v['expected_result']??'')),'movementId'=>sanitize_key((string)($v['movement_id']??'')),'justification'=>sanitize_textarea_field((string)($v['justification']??''))];}return$o;}
}
