<?php

declare(strict_types=1);

namespace VerbumStudio\Api;

use VerbumStudio\Auth\Capabilities;
use VerbumStudio\Core\Config;
use VerbumStudio\Exceptions\ValidationError;
use VerbumStudio\Library\FoundationIntentionRepository;
use VerbumStudio\Library\FoundationReaderResultRepository;
use VerbumStudio\Library\FoundationTruthCentralRepository;
use VerbumStudio\Library\LibraryRepository;
use VerbumStudio\Library\StructureDirectionRepository;

final class StructureDirectionController
{
    private Config $config;private ResponseFactory $responses;private Capabilities $capabilities;private LibraryRepository $library;private StructureDirectionRepository $direction;private FoundationIntentionRepository $intention;private FoundationReaderResultRepository $reader;private FoundationTruthCentralRepository $truth;
    public function __construct(Config $config,ResponseFactory $responses,Capabilities $capabilities,LibraryRepository $library,StructureDirectionRepository $direction,FoundationIntentionRepository $intention,FoundationReaderResultRepository $reader,FoundationTruthCentralRepository $truth){$this->config=$config;$this->responses=$responses;$this->capabilities=$capabilities;$this->library=$library;$this->direction=$direction;$this->intention=$intention;$this->reader=$reader;$this->truth=$truth;}
    public function register():void{add_action('rest_api_init',function():void{$n=$this->config->get('api_namespace');$p=[$this,'canAccess'];$b='/books/(?P<id>\d+)/structure/direction';register_rest_route($n,$b,[['methods'=>'GET','callback'=>[$this,'show'],'permission_callback'=>$p],['methods'=>'PATCH','callback'=>[$this,'save'],'permission_callback'=>$p]]);register_rest_route($n,$b.'/complete',['methods'=>'POST','callback'=>[$this,'complete'],'permission_callback'=>$p]);register_rest_route($n,$b.'/coherence',['methods'=>'POST','callback'=>[$this,'coherence'],'permission_callback'=>$p]);});}
    public function canAccess():bool{return$this->capabilities->currentUserCanAccess();}
    public function show(\WP_REST_Request $r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->direction->data($id));}catch(\Throwable $e){return$this->responses->error($e);}}
    public function save(\WP_REST_Request $r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->direction->save($id,$this->payload($r)));}catch(\Throwable $e){return$this->responses->error($e);}}
    public function complete(\WP_REST_Request $r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);return$this->responses->success($this->direction->complete($id));}catch(\Throwable $e){return$this->responses->error($e);}}
    public function coherence(\WP_REST_Request $r):\WP_REST_Response{try{$id=(int)$r['id'];$this->owned($id);$p=$this->payload($r);$i=$this->intention->data($id);$rr=$this->reader->data($id);$t=$this->truth->data($id);$input="TESE\n".wp_strip_all_tags((string)$t['thesisHtml'])."\n\nFRASE-SÍNTESE\n".$t['synthesisPhrase']."\n\nPROBLEMA\n".$i['problem']."\n\nPROPÓSITO\n".$i['purpose']."\n\nOBJETIVO GERAL\n".$i['generalObjective']."\n\nOBJETIVOS\n".implode("\n",array_map(static fn($x):string=>(string)($x['text']??''),(array)$i['specificObjectives']))."\n\nPÚBLICO\n".$rr['audience']."\n\nNECESSIDADES\n".$rr['needs']."\n\nTRANSFORMAÇÃO\n".$rr['transformation']."\n\nDIFERENCIAL\n".$rr['differential']."\n\nLIMITES\n".$rr['scopeIncluded']." | ".$rr['scopeExcluded']."\n\nEIXO\n".($p['axis']??'')."\n\nFIO CONDUTOR\n".($p['thread']??'')."\n\nORDEM TEOLÓGICA\n".$this->listText($p['theological_order']??[])."\n\nPONTO DE PARTIDA\n".($p['starting_point']??'')."\n\nPONTO DE CHEGADA\n".($p['arrival_point']??'')."\n\nMOVIMENTO\n".$this->listText($p['movement']??[]);$j=$this->callAi('Analise a coerência da Direção da obra com a Fundação. Avalie unidade, percurso, lacunas, repetições, contradições e respeito aos limites. Não invente doutrina, referências ou fatos. Responda somente JSON válido com arrays coherent_points, attention_points, contradictions, gaps e suggestions. Observações usam fields e observation. Sugestões usam field (axis, thread, starting_point, arrival_point), current_text, suggested_text e reason.',$input,2400);return$this->responses->success(['coherentPoints'=>$this->observations($j['coherent_points']??[]),'attentionPoints'=>$this->observations($j['attention_points']??[]),'contradictions'=>$this->observations($j['contradictions']??[]),'gaps'=>$this->observations($j['gaps']??[]),'suggestions'=>$this->suggestions($j['suggestions']??[])]);}catch(\Throwable $e){return$this->responses->error($e);}}
    private function owned(int $id):void{$this->library->workspaceForBook(get_current_user_id(),$id);}
    /** @return array<string,mixed> */
    private function payload(\WP_REST_Request $r):array{$p=$r->get_json_params();$p=is_array($p)?$p:[];$o=[];foreach(['axis','thread','starting_point','arrival_point']as$f)if(array_key_exists($f,$p))$o[$f]=sanitize_textarea_field((string)$p[$f]);foreach(['theological_order','movement']as$f)if(array_key_exists($f,$p)){$o[$f]=[];foreach(is_array($p[$f])?$p[$f]:[]as$i=>$x)if(is_array($x))$o[$f][]=['id'=>sanitize_key((string)($x['id']??'')),'text'=>sanitize_text_field((string)($x['text']??'')),'order'=>max(1,(int)($x['order']??($i+1)))];}if(array_key_exists('base_revision',$p))$o['base_revision']=max(0,(int)$p['base_revision']);return$o;}
    /** @param mixed $items */ private function listText($items):string{return implode(' → ',array_values(array_filter(array_map(static fn($x):string=>is_array($x)?trim((string)($x['text']??'')):'',is_array($items)?$items:[]))));}
    /** @return array<string,mixed> */ private function callAi(string $ins,string $input,int $max):array{$key=trim((string)$this->config->get('openai_api_key',''));if($key==='')throw new ValidationError('A Assistência de coerência está indisponível porque VERBUM_OPENAI_API_KEY ainda não foi configurada no servidor.');$res=wp_remote_post('https://api.openai.com/v1/responses',['timeout'=>60,'headers'=>['Authorization'=>'Bearer '.$key,'Content-Type'=>'application/json'],'body'=>wp_json_encode(['model'=>'gpt-5.6-luna','instructions'=>$ins,'input'=>$input,'max_output_tokens'=>$max])]);if(is_wp_error($res))throw new ValidationError('Não foi possível acessar a inteligência artificial neste momento.');$status=(int)wp_remote_retrieve_response_code($res);$body=json_decode((string)wp_remote_retrieve_body($res),true);if($status<200||$status>=300||!is_array($body))throw new ValidationError('A inteligência artificial não conseguiu concluir a solicitação. Tente novamente.');$text='';foreach((array)($body['output']??[])as$item){if(!is_array($item)||($item['type']??'')!=='message')continue;foreach((array)($item['content']??[])as$c)if(is_array($c)&&($c['type']??'')==='output_text')$text.=(string)($c['text']??'');}if(preg_match('/^```(?:json)?\s*(.*?)\s*```$/s',trim($text),$m))$text=trim((string)($m[1]??''));$j=json_decode(trim($text),true);if(!is_array($j))throw new ValidationError('A inteligência artificial retornou uma resposta inválida. Tente novamente.');return$j;}
    /** @param mixed $items @return array<int,array<string,mixed>> */ private function observations($items):array{$o=[];foreach(is_array($items)?$items:[]as$x){if(!is_array($x))continue;$v=trim(sanitize_textarea_field((string)($x['observation']??'')));if($v!=='')$o[]=['fields'=>array_values(array_filter(array_map(static fn($f):string=>sanitize_text_field((string)$f),(array)($x['fields']??[])))),'observation'=>$v];}return$o;}
    /** @param mixed $items @return array<int,array<string,string>> */ private function suggestions($items):array{$o=[];foreach(is_array($items)?$items:[]as$x){if(!is_array($x))continue;$f=sanitize_key((string)($x['field']??''));$v=trim(sanitize_textarea_field((string)($x['suggested_text']??'')));if(!in_array($f,['axis','thread','starting_point','arrival_point'],true)||$v==='')continue;$o[]=['field'=>$f,'currentText'=>trim(sanitize_textarea_field((string)($x['current_text']??''))),'suggestedText'=>$v,'reason'=>trim(sanitize_textarea_field((string)($x['reason']??'')))];}return$o;}
}
