import { useEffect, useMemo, useState } from 'react';
import { completeChapterPreparation, getChapterPreparation, saveChapterPreparation } from '../services/library-service';
import type { ChapterPreparationInput, ChapterPreparationProgress, DevelopmentChapter, WorkDevelopmentProgress } from '../types/verbum';

type Props = { bookId:string; chapter:DevelopmentChapter; onChapterChange:(chapter:DevelopmentChapter)=>void; onDevelopmentChange:(development:WorkDevelopmentProgress)=>void };
const emptyInput:ChapterPreparationInput={subtitle:'',objective:'',central_question:'',purpose:'',thesis:'',main_message:'',guiding_phrase:'',keywords:[],structure_items:[],source_categories:[],spiritual_intention:'',virtue:'',writing_prayer:'',notes:''};

export function ChapterPreparationStage({bookId,chapter,onChapterChange,onDevelopmentChange}:Props){
 const [data,setData]=useState<ChapterPreparationProgress|null>(null); const [form,setForm]=useState<ChapterPreparationInput>(emptyInput); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [error,setError]=useState('');
 useEffect(()=>{let active=true;setData(null);setError('');getChapterPreparation(bookId,chapter.id).then((result)=>{if(!active)return;setData(result);const v=result.values;setForm({subtitle:v.subtitle,objective:v.objective,central_question:v.centralQuestion,purpose:v.purpose,thesis:v.thesis,main_message:v.mainMessage,guiding_phrase:v.guidingPhrase,keywords:v.keywords,structure_items:v.structureItems,source_categories:v.sourceCategories,spiritual_intention:v.spiritualIntention,virtue:v.virtue,writing_prayer:v.writingPrayer,notes:v.notes});}).catch((cause)=>{if(active)setError(cause instanceof Error?cause.message:'Não foi possível carregar a Preparação.');});return()=>{active=false};},[bookId,chapter.id]);
 const ready=useMemo(()=>Boolean(form.objective.trim()&&form.central_question.trim()&&form.thesis.trim()&&form.structure_items.some((item)=>item.text.trim())&&form.source_categories.length),[form]);
 function patch<K extends keyof ChapterPreparationInput>(key:K,value:ChapterPreparationInput[K]){setForm((current)=>({...current,[key]:value}));setMessage('');}
 function addStructure(){patch('structure_items',[...form.structure_items,{id:`new-${Date.now()}`,text:'',order:form.structure_items.length+1}]);}
 function updateStructure(index:number,text:string){patch('structure_items',form.structure_items.map((item,i)=>i===index?{...item,text}:item));}
 function moveStructure(index:number,direction:-1|1){const next=index+direction;if(next<0||next>=form.structure_items.length)return;const items=[...form.structure_items];[items[index],items[next]]=[items[next],items[index]];patch('structure_items',items.map((item,i)=>({...item,order:i+1})));}
 function removeStructure(index:number){patch('structure_items',form.structure_items.filter((_,i)=>i!==index).map((item,i)=>({...item,order:i+1})));}
 async function save(){setSaving(true);setError('');setMessage('');try{const result=await saveChapterPreparation(bookId,chapter.id,form);setData(result.preparation);onChapterChange(result.chapter);onDevelopmentChange(result.developmentStage);setMessage('Alterações salvas.');}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível salvar a Preparação.');}finally{setSaving(false)}}
 async function complete(){if(!ready||saving)return;setSaving(true);setError('');setMessage('');try{await saveChapterPreparation(bookId,chapter.id,form);const result=await completeChapterPreparation(bookId,chapter.id);setData(result.preparation);onChapterChange(result.chapter);onDevelopmentChange(result.developmentStage);setMessage('Preparação concluída. Pesquisa liberada.');}catch(cause){setError(cause instanceof Error?cause.message:'Não foi possível concluir a Preparação.');}finally{setSaving(false)}}
 if(!data&&!error)return <div className="verbum-preparation-state">Carregando Preparação do Capítulo...</div>; if(!data)return <div className="verbum-preparation-state is-error">{error}</div>;
 return <div className="verbum-preparation-layout"><div className="verbum-preparation-main">
  <section className="verbum-preparation-card"><div className="verbum-preparation-direction-head"><div><span>Direção do Capítulo</span><h3>{chapter.title}</h3></div><small>Defina o mínimo necessário antes de pesquisar e escrever.</small></div><label><span>Objetivo do capítulo *</span><textarea value={form.objective} onChange={(e)=>patch('objective',e.target.value)} placeholder="O que este capítulo precisa alcançar dentro da obra?"/></label><label><span>Pergunta central *</span><textarea value={form.central_question} onChange={(e)=>patch('central_question',e.target.value)} placeholder="Qual pergunta principal este capítulo pretende responder?"/></label><label><span>Tese do capítulo *</span><textarea value={form.thesis} onChange={(e)=>patch('thesis',e.target.value)} placeholder="Qual ideia central será desenvolvida neste capítulo?"/></label></section>
  <section className="verbum-preparation-card"><div className="verbum-preparation-card-heading"><div><h3>Estrutura do Capítulo</h3><p>Liste somente os pontos que precisam ser desenvolvidos durante a escrita.</p></div><button type="button" onClick={addStructure}>+ Adicionar ponto</button></div><div className="verbum-preparation-structure">{form.structure_items.length===0?<div className="verbum-preparation-empty">Nenhum ponto adicionado.</div>:form.structure_items.map((item,index)=><div className="verbum-preparation-structure-item" key={item.id||index}><span>{index+1}</span><input value={item.text} onChange={(e)=>updateStructure(index,e.target.value)} placeholder="Ponto a desenvolver"/><button type="button" disabled={index===0} onClick={()=>moveStructure(index,-1)}>↑</button><button type="button" disabled={index===form.structure_items.length-1} onClick={()=>moveStructure(index,1)}>↓</button><button type="button" className="is-danger" onClick={()=>removeStructure(index)}>Remover</button></div>)}</div></section>
  <section className="verbum-preparation-card"><h3>Pesquisa necessária *</h3><p className="verbum-preparation-help">Marque as categorias de fonte que deverão orientar a próxima etapa.</p><div className="verbum-preparation-sources">{data.sourceOptions.map((option)=><label key={option.key}><input type="checkbox" checked={form.source_categories.includes(option.key)} onChange={(e)=>patch('source_categories',e.target.checked?[...form.source_categories,option.key]:form.source_categories.filter((key)=>key!==option.key))}/><span>{option.label}</span></label>)}</div></section>
  <details className="verbum-preparation-card verbum-preparation-optional"><summary><div><h3>Intenção espiritual</h3><p>Opcional para obras religiosas.</p></div><span>Expandir</span></summary><label><span>Intenção</span><textarea value={form.spiritual_intention} onChange={(e)=>patch('spiritual_intention',e.target.value)}/></label><label><span>Virtude relacionada</span><input value={form.virtue} onChange={(e)=>patch('virtue',e.target.value)}/></label><label><span>Oração antes da escrita</span><textarea value={form.writing_prayer} onChange={(e)=>patch('writing_prayer',e.target.value)}/></label></details>
  <details className="verbum-preparation-card verbum-preparation-optional"><summary><div><h3>Aprofundar preparação</h3><p>Campos anteriores preservados para uso opcional.</p></div><span>Expandir</span></summary><label><span>Subtítulo</span><input value={form.subtitle} onChange={(e)=>patch('subtitle',e.target.value)}/></label><label><span>Finalidade</span><textarea value={form.purpose} onChange={(e)=>patch('purpose',e.target.value)}/></label><label><span>Mensagem principal</span><textarea value={form.main_message} onChange={(e)=>patch('main_message',e.target.value)}/></label><label><span>Frase norteadora</span><input value={form.guiding_phrase} onChange={(e)=>patch('guiding_phrase',e.target.value)}/></label><label><span>Palavras-chave</span><input value={form.keywords.join(', ')} onChange={(e)=>patch('keywords',e.target.value.split(',').map((value)=>value.trim()).filter(Boolean))}/></label><label><span>Observações</span><textarea value={form.notes} onChange={(e)=>patch('notes',e.target.value)}/></label></details>
  {error&&<p className="verbum-preparation-message is-error">{error}</p>}{message&&<p className="verbum-preparation-message is-success">{message}</p>}<div className="verbum-preparation-actions"><button type="button" className="verbum-secondary-button" disabled={saving} onClick={save}>{saving?'Salvando…':'Salvar'}</button><button type="button" className="verbum-primary-button" disabled={!ready||saving||data.completed} onClick={complete}>{data.completed?'Preparação concluída ✓':'Concluir Preparação e ir para Pesquisa ›'}</button></div>
 </div><aside className="verbum-preparation-progress"><div className="verbum-preparation-progress-top"><div><span>{ready?'Preparação pronta para Pesquisa':'Preparação do capítulo'}</span><strong>{data.progress}%</strong></div><div className="verbum-preparation-progress-bar"><span style={{width:`${data.progress}%`}}/></div><small>{data.completedCount} de {data.total} essenciais concluídos</small></div><div className="verbum-preparation-checklist">{data.checklist.map((item)=><div key={item.key} className={item.completed?'is-complete':''}><span>{item.completed?'✓':''}</span><p>{item.label}</p></div>)}</div><p className="verbum-preparation-required">A preparação é um plano breve. Campos opcionais não bloqueiam o avanço.</p></aside></div>;
}
