import { useEffect, useMemo, useState } from 'react';
import {
  assistLayoutStage, completeLayoutStage, createLayoutIssue, deleteLayoutIssue, generateLayoutProof,
  getLayoutPreview, getLayoutStage, saveLayoutStage, updateLayoutIssue,
} from '../services/layout-stage-service';
import type { LayoutConfig, LayoutPreview, LayoutStage as LayoutStageData } from '../types/layout-stage';
import type { WorkStageKey, WorkWorkspaceData } from '../types/verbum';
import { WorkspaceFooter } from './WorkspaceFooter';

type Props = { workspace: WorkWorkspaceData; onWorkspaceChange: (workspace: WorkWorkspaceData) => void; onStageChange: (stage: WorkStageKey) => void; onPersisted: () => void | Promise<void> };
const presets = ['Clássico', 'Contemporâneo', 'Minimalista', 'Acadêmico', 'Devocional', 'Literário'];
const fonts = ['Georgia', 'Times New Roman', 'Arial', 'Verdana'];
const str = (value: unknown) => typeof value === 'string' ? value : '';

export function LayoutStage({ workspace, onWorkspaceChange, onStageChange, onPersisted }: Props) {
  const [data, setData] = useState<LayoutStageData | null>(null);
  const [preview, setPreview] = useState<LayoutPreview | null>(null);
  const [pageIndex, setPageIndex] = useState(0);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [issueCategory, setIssueCategory] = useState('typography');
  const [issueText, setIssueText] = useState('');
  const [proofNote, setProofNote] = useState('');
  const [assistant, setAssistant] = useState('');

  useEffect(() => { let alive = true; getLayoutStage(workspace.book.id).then((result) => alive && setData(result)).catch((cause) => alive && setError(cause instanceof Error ? cause.message : 'Não foi possível carregar a Diagramação.')); return () => { alive = false; }; }, [workspace.book.id]);

  const page = preview?.pages[pageIndex];
  const secondPage = data?.config.preview.spread ? preview?.pages[pageIndex + 1] : undefined;
  const formatStyle = useMemo(() => data ? ({ '--layout-ratio': `${data.config.format.widthMm}/${data.config.format.heightMm}`, fontFamily: data.config.typography.bodyFont, fontSize: `${Math.max(8, data.config.typography.bodySizePt - 2)}px`, lineHeight: data.config.typography.lineHeight } as React.CSSProperties) : {}, [data]);

  async function mutate(action: () => Promise<{ layoutStage: LayoutStageData; workspace: WorkWorkspaceData }>) {
    if (busy) return; setBusy(true); setError('');
    try { const result = await action(); setData(result.layoutStage); onWorkspaceChange(result.workspace); await onPersisted(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível concluir a operação.'); }
    finally { setBusy(false); }
  }
  async function persist(next: LayoutStageData) { setData(next); await mutate(() => saveLayoutStage(workspace.book.id, next.config, next.flags, next.finalConfirmation)); }
  function changeConfig(update: (config: LayoutConfig) => LayoutConfig) { if (!data) return; const next = { ...data, config: update(data.config) }; void persist(next); }
  function setPreset(preset: string) {
    changeConfig((config) => ({ ...config, preset, typography: { ...config.typography, bodyFont: preset === 'Acadêmico' ? 'Times New Roman' : preset === 'Contemporâneo' || preset === 'Minimalista' ? 'Arial' : 'Georgia', headingFont: preset === 'Contemporâneo' ? 'Arial' : 'Georgia' }, chapter: { ...config.chapter, titleAlign: preset === 'Contemporâneo' ? 'left' : 'center', dropCaps: preset === 'Clássico' || preset === 'Devocional' || preset === 'Literário' } }));
  }
  async function loadPreview() { setBusy(true); setError(''); try { const result = await getLayoutPreview(workspace.book.id); setPreview(result); setPageIndex(0); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível gerar a prévia.'); } finally { setBusy(false); } }

  if (!data) return <section className="verbum-stage-content"><div className={`verbum-layout-state${error ? ' is-error' : ''}`}>{error || 'Carregando Diagramação da Obra...'}</div></section>;
  const identity = data.editorial.identity;
  return <>
    <section className="verbum-stage-content verbum-layout-stage">
      <header className="verbum-layout-heading"><div><span className="verbum-eyebrow">Etapa 9 de 11</span><h2>Diagramação da Obra</h2><p>Transforme a versão editorial aprovada em um projeto de livro paginado.</p></div><div className="verbum-layout-baseline"><small>Versão para Diagramação</small><strong>{data.version.number} — {data.version.name}</strong><span>{data.chapterCount} capítulos · {data.version.wordCount.toLocaleString('pt-BR')} palavras</span><code>{data.version.hash.slice(0, 18)}…</code></div></header>
      {!data.baselineValid && <div className="verbum-layout-warning"><strong>A baseline editorial não está mais válida.</strong><p>Retorne à Mesa Editorial antes de continuar.</p></div>}
      <div className="verbum-layout-stats"><article><strong>{data.config.format.name}</strong><span>Formato</span></article><article><strong>{data.pageCount}</strong><span>Páginas estimadas</span></article><article><strong>{data.chapterCount}/{data.chapterCount}</strong><span>Capítulos</span></article><article><strong>{data.openIssueCount}</strong><span>Pendências</span></article><article><strong>{data.proofs.length}</strong><span>Provas</span></article><article><strong>{data.progress}%</strong><span>Progresso</span></article></div>

      <div className="verbum-layout-grid">
        <main>
          <section className="verbum-layout-card"><div className="verbum-layout-card-head"><div><h3>Modelo visual</h3><p>Escolha um ponto de partida e personalize os estilos.</p></div></div><div className="verbum-layout-presets">{presets.map((preset) => <button type="button" className={data.config.preset === preset ? 'is-active' : ''} disabled={busy || data.completed} onClick={() => setPreset(preset)} key={preset}>{preset}</button>)}</div></section>

          <section className="verbum-layout-card"><h3>Formato, margens e sangria</h3><div className="verbum-layout-form cols-4"><label>Formato<select value={data.config.format.name} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, format: { ...c.format, name: e.target.value, widthMm: e.target.value === '16 × 23 cm' ? 160 : e.target.value === 'A5' ? 148 : 140, heightMm: e.target.value === '16 × 23 cm' ? 230 : e.target.value === 'A5' ? 210 : 210 } }))}><option>14 × 21 cm</option><option>16 × 23 cm</option><option>A5</option><option>Personalizado</option></select></label><NumberField label="Largura (mm)" value={data.config.format.widthMm} onChange={(v) => changeConfig((c) => ({ ...c, format: { ...c.format, widthMm: v } }))} /><NumberField label="Altura (mm)" value={data.config.format.heightMm} onChange={(v) => changeConfig((c) => ({ ...c, format: { ...c.format, heightMm: v } }))} /><NumberField label="Sangria (mm)" value={data.config.format.bleedMm} onChange={(v) => changeConfig((c) => ({ ...c, format: { ...c.format, bleedMm: v } }))} /></div><div className="verbum-layout-form cols-4"><NumberField label="Superior" value={data.config.margins.topMm} onChange={(v) => changeConfig((c) => ({ ...c, margins: { ...c.margins, topMm: v } }))} /><NumberField label="Inferior" value={data.config.margins.bottomMm} onChange={(v) => changeConfig((c) => ({ ...c, margins: { ...c.margins, bottomMm: v } }))} /><NumberField label="Interna" value={data.config.margins.innerMm} onChange={(v) => changeConfig((c) => ({ ...c, margins: { ...c.margins, innerMm: v } }))} /><NumberField label="Externa" value={data.config.margins.outerMm} onChange={(v) => changeConfig((c) => ({ ...c, margins: { ...c.margins, outerMm: v } }))} /></div><Toggle checked={data.config.margins.mirrored} label="Usar margens espelhadas para impressão frente e verso" onChange={(v) => changeConfig((c) => ({ ...c, margins: { ...c.margins, mirrored: v } }))} /></section>

          <section className="verbum-layout-card"><h3>Tipografia e parágrafos</h3><div className="verbum-layout-form cols-3"><label>Fonte do corpo<select value={data.config.typography.bodyFont} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, typography: { ...c.typography, bodyFont: e.target.value } }))}>{fonts.map((font) => <option key={font}>{font}</option>)}</select></label><NumberField label="Corpo (pt)" value={data.config.typography.bodySizePt} step={0.5} onChange={(v) => changeConfig((c) => ({ ...c, typography: { ...c.typography, bodySizePt: v } }))} /><NumberField label="Entrelinha" value={data.config.typography.lineHeight} step={0.05} onChange={(v) => changeConfig((c) => ({ ...c, typography: { ...c.typography, lineHeight: v } }))} /><NumberField label="Recuo 1ª linha (cm)" value={data.config.paragraph.firstLineCm} step={0.1} onChange={(v) => changeConfig((c) => ({ ...c, paragraph: { ...c.paragraph, firstLineCm: v } }))} /><NumberField label="Espaço depois (pt)" value={data.config.paragraph.spaceAfterPt} onChange={(v) => changeConfig((c) => ({ ...c, paragraph: { ...c.paragraph, spaceAfterPt: v } }))} /><label>Alinhamento<select value={data.config.typography.align} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, typography: { ...c.typography, align: e.target.value } }))}><option value="justify">Justificado</option><option value="left">Esquerda</option></select></label></div><div className="verbum-layout-toggles"><Toggle checked={data.config.paragraph.noIndentAfterHeading} label="Sem recuo após títulos" onChange={(v) => changeConfig((c) => ({ ...c, paragraph: { ...c.paragraph, noIndentAfterHeading: v } }))} /><Toggle checked={data.config.paragraph.hyphenation} label="Hifenização automática" onChange={(v) => changeConfig((c) => ({ ...c, paragraph: { ...c.paragraph, hyphenation: v } }))} /><Toggle checked={data.config.paragraph.widowsOrphans} label="Controle de viúvas e órfãs" onChange={(v) => changeConfig((c) => ({ ...c, paragraph: { ...c.paragraph, widowsOrphans: v } }))} /></div></section>

          <section className="verbum-layout-card"><h3>Página-mestre e abertura de capítulos</h3><div className="verbum-layout-form cols-2"><TextField label="Cabeçalho página par" value={data.config.masterPage.evenHeader} onChange={(v) => changeConfig((c) => ({ ...c, masterPage: { ...c.masterPage, evenHeader: v } }))} /><TextField label="Cabeçalho página ímpar" value={data.config.masterPage.oddHeader} onChange={(v) => changeConfig((c) => ({ ...c, masterPage: { ...c.masterPage, oddHeader: v } }))} /><label>Paginação<select value={data.config.masterPage.pageNumberPosition} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, masterPage: { ...c.masterPage, pageNumberPosition: e.target.value } }))}><option value="bottom-outer">Inferior externa</option><option value="bottom-center">Inferior centralizada</option><option value="top-outer">Superior externa</option><option value="hidden">Ocultar</option></select></label><label>Início de capítulo<select value={data.config.chapter.start} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, chapter: { ...c.chapter, start: e.target.value } }))}><option value="new-page">Nova página</option><option value="odd-page">Sempre página ímpar</option></select></label></div><div className="verbum-layout-toggles"><Toggle checked={data.config.masterPage.frontMatterRoman} label="Numeração romana no pré-textual" onChange={(v) => changeConfig((c) => ({ ...c, masterPage: { ...c.masterPage, frontMatterRoman: v } }))} /><Toggle checked={data.config.masterPage.hideOnChapterOpening} label="Ocultar número na abertura" onChange={(v) => changeConfig((c) => ({ ...c, masterPage: { ...c.masterPage, hideOnChapterOpening: v } }))} /><Toggle checked={data.config.chapter.dropCaps} label="Usar capitular" onChange={(v) => changeConfig((c) => ({ ...c, chapter: { ...c.chapter, dropCaps: v } }))} /></div></section>

          <section className="verbum-layout-card"><h3>Sumário, notas e estilos especiais</h3><div className="verbum-layout-toggles"><Toggle checked={data.config.toc.chapters} label="Capítulos no sumário" onChange={(v) => changeConfig((c) => ({ ...c, toc: { ...c.toc, chapters: v } }))} /><Toggle checked={data.config.toc.subchapters} label="Subcapítulos no sumário" onChange={(v) => changeConfig((c) => ({ ...c, toc: { ...c.toc, subchapters: v } }))} /><Toggle checked={data.config.religiousStyles.verse} label="Estilo Versículo" onChange={(v) => changeConfig((c) => ({ ...c, religiousStyles: { ...c.religiousStyles, verse: v } }))} /><Toggle checked={data.config.religiousStyles.catechism} label="Estilo Catecismo" onChange={(v) => changeConfig((c) => ({ ...c, religiousStyles: { ...c.religiousStyles, catechism: v } }))} /></div><label className="verbum-layout-inline-select">Notas<select value={data.config.notes.mode} disabled={busy || data.completed} onChange={(e) => changeConfig((c) => ({ ...c, notes: { mode: e.target.value } }))}><option value="footnotes">Notas de rodapé</option><option value="endnotes">Notas finais</option></select></label></section>

          <section className="verbum-layout-card"><div className="verbum-layout-card-head"><div><h3>Prévia do miolo</h3><p>Visualização paginada aproximada. O PDF de prova não é certificado como PDF/X.</p></div><div><button type="button" disabled={busy} onClick={() => void loadPreview()}>Visualizar livro</button><button type="button" disabled={!preview} onClick={() => changeConfig((c) => ({ ...c, preview: { spread: !c.preview.spread } }))}>{data.config.preview.spread ? 'Página simples' : 'Páginas espelhadas'}</button></div></div>{preview ? <div className="verbum-layout-preview"><div className="verbum-layout-page-nav"><button disabled={pageIndex === 0} onClick={() => setPageIndex(Math.max(0, pageIndex - (data.config.preview.spread ? 2 : 1)))}>‹</button><span>{pageIndex + 1}{data.config.preview.spread && secondPage ? `–${pageIndex + 2}` : ''} / {preview.pageCount}</span><button disabled={pageIndex >= preview.pageCount - 1} onClick={() => setPageIndex(Math.min(preview.pageCount - 1, pageIndex + (data.config.preview.spread ? 2 : 1)))}>›</button></div><div className={`verbum-layout-pages${data.config.preview.spread ? ' is-spread' : ''}`}>{page && <PreviewPage page={page} style={formatStyle} />}{secondPage && <PreviewPage page={secondPage} style={formatStyle} />}</div><div className="verbum-layout-map">{preview.pages.map((item, index) => <button className={index === pageIndex ? 'is-active' : ''} key={`${item.number}-${index}`} onClick={() => setPageIndex(index)}><span>{item.number}</span><small>{item.title || item.kind}</small></button>)}</div></div> : <p className="verbum-layout-empty">Gere a prévia para navegar pelo mapa de páginas.</p>}</section>

          <section className="verbum-layout-card"><h3>Pendências de Diagramação</h3><div className="verbum-layout-issue-form"><select value={issueCategory} onChange={(e) => setIssueCategory(e.target.value)}>{data.issueCategories.map((item) => <option key={item.key} value={item.key}>{item.label}</option>)}</select><input value={issueText} onChange={(e) => setIssueText(e.target.value)} placeholder="Descreva a pendência..." /><button disabled={!issueText.trim() || busy || data.completed} onClick={() => void mutate(() => createLayoutIssue(workspace.book.id, issueCategory, issueText)).then(() => setIssueText(''))}>Registrar</button></div><div className="verbum-layout-issues">{data.issues.length === 0 ? <p>Nenhuma pendência registrada.</p> : data.issues.map((item) => <article className={item.status === 'resolved' ? 'is-resolved' : ''} key={item.id}><div><strong>{item.categoryLabel}</strong><p>{item.description}</p></div><div>{item.status === 'open' ? <button disabled={busy || data.completed} onClick={() => void mutate(() => updateLayoutIssue(workspace.book.id, item.id, 'resolved'))}>Resolver</button> : <button disabled={busy || data.completed} onClick={() => void mutate(() => updateLayoutIssue(workspace.book.id, item.id, 'open'))}>Reabrir</button>}<button className="is-danger" disabled={busy || data.completed} onClick={() => window.confirm('Excluir esta pendência?') && void mutate(() => deleteLayoutIssue(workspace.book.id, item.id))}>Excluir</button></div></article>)}</div></section>
        </main>

        <aside>
          <section className="verbum-layout-card verbum-layout-brief"><h3>Briefing recebido</h3><p><b>Título:</b> {str(identity.titleFinal)}</p><p><b>Subtítulo:</b> {str(identity.subtitleFinal) || '—'}</p><p><b>Estilo:</b> {str(data.editorial.layoutBrief.style) || '—'}</p><p><b>Formato pretendido:</b> {str(data.editorial.edition.trimSize) || '—'}</p><p><b>Capa:</b> {str(data.editorial.coverBrief.concept) || 'Briefing disponível na Mesa Editorial'}</p></section>
          <section className="verbum-layout-card verbum-layout-proof"><h3>Provas de Diagramação</h3><textarea value={proofNote} onChange={(e) => setProofNote(e.target.value)} placeholder="Observação da prova..." /><button disabled={busy || data.completed} onClick={() => void mutate(() => generateLayoutProof(workspace.book.id, proofNote)).then(() => setProofNote(''))}>Gerar PDF de Prova</button><p className="verbum-layout-proof-note">O arquivo recebe a marca “PROVA — NÃO PUBLICAR” e não é declarado PDF/X.</p>{data.proofs.map((proof) => <article key={proof.id}><div><strong>{proof.label}</strong><span>{proof.pageCount} páginas · {new Date(proof.createdAt).toLocaleString('pt-BR')}</span></div><a href={proof.url} target="_blank" rel="noreferrer">Abrir PDF</a></article>)}</section>
          <section className="verbum-layout-card verbum-layout-assistant"><h3>Assistente de Diagramação</h3><p>As sugestões nunca são aplicadas automaticamente.</p><div>{[['typography','Combinação tipográfica'],['hierarchy','Hierarquia visual'],['format','Formato e margens'],['chapter_opening','Abertura de capítulos'],['quotes','Citações'],['consistency','Consistência']].map(([key,label]) => <button key={key} disabled={busy || data.completed} onClick={() => { setBusy(true); assistLayoutStage(workspace.book.id, key).then((result) => setAssistant(result.suggestion)).catch((cause) => setError(cause instanceof Error ? cause.message : 'Não foi possível usar o Assistente.')).finally(() => setBusy(false)); }}>{label}</button>)}</div>{assistant && <div className="verbum-layout-assistant-result"><textarea value={assistant} onChange={(e) => setAssistant(e.target.value)} /><button onClick={() => setAssistant('')}>Descartar</button></div>}</section>
          <section className="verbum-layout-card verbum-layout-progress"><div className="verbum-layout-card-head"><h3>Checklist visual</h3><strong>{data.progress}%</strong></div><div className="verbum-layout-progressbar"><span style={{ width: `${data.progress}%` }} /></div>{data.checklist.map((item) => { const manual = !item.automatic && item.key !== 'completed'; const checked = manual ? Boolean(data.flags[item.key]) : item.completed; return <label className={checked ? 'is-complete' : ''} key={item.key}><input type="checkbox" checked={checked} disabled={!manual || busy || data.completed} onChange={(e) => { if (!manual) return; const flags = { ...data.flags, [item.key]: e.target.checked }; void persist({ ...data, flags }); }} /><span>{item.label}</span></label>; })}<label className={data.finalConfirmation ? 'is-complete is-confirmation' : 'is-confirmation'}><input type="checkbox" checked={data.finalConfirmation} disabled={busy || data.completed} onChange={(e) => void persist({ ...data, finalConfirmation: e.target.checked })} /><span>Li e conferi a prévia integral e aprovo a paginação.</span></label><button className="verbum-primary-button" disabled={!data.ready || busy || data.completed} onClick={() => void mutate(() => completeLayoutStage(workspace.book.id)).then(() => onStageChange('legal'))}>{data.completed ? 'Diagramação aprovada ✓' : 'Concluir Diagramação'}</button></section>
        </aside>
      </div>
      {error && <p className="verbum-layout-message is-error">{error}</p>}
    </section>
    <WorkspaceFooter canGoBack onPrevious={() => onStageChange('editorial_desk')} onBackToLibrary={() => onStageChange('editorial_desk')} />
  </>;
}

function NumberField({ label, value, step = 1, onChange }: { label: string; value: number; step?: number; onChange: (value: number) => void }) { return <label>{label}<input type="number" step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} /></label>; }
function TextField({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<input value={value} onChange={(e) => onChange(e.target.value)} /></label>; }
function Toggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: (value: boolean) => void }) { return <label className="verbum-layout-toggle"><input type="checkbox" checked={checked} onChange={(e) => onChange(e.target.checked)} /><span>{label}</span></label>; }
function PreviewPage({ page, style }: { page: { number: number; title: string; content: string; kind: string }; style: React.CSSProperties }) { return <article className={`verbum-layout-page kind-${page.kind}`} style={style}><header>{page.title && <h4>{page.title}</h4>}</header><p>{page.content}</p><footer>{page.number}</footer></article>; }
