import { useEffect, useState } from 'react';
import {
  assistPublicationStage, completePublicationStage, createPublicationChannel, createPublicationTask,
  deletePublicationChannel, deletePublicationTask, getPublicationStage, registerPublicationUpdate,
  savePublicationStage, updatePublicationChannel, updatePublicationTask,
} from '../services/publication-stage-service';
import type { PublicationMutationResponse, PublicationStage as PublicationStageData, PublicationState } from '../types/publication-stage';
import type { WorkStageKey, WorkWorkspaceData } from '../types/verbum';
import { WorkspaceFooter } from './WorkspaceFooter';

type Props = { workspace: WorkWorkspaceData; onWorkspaceChange: (workspace: WorkWorkspaceData) => void; onStageChange: (stage: WorkStageKey) => void; onPersisted: () => void | Promise<void> };
const text = (value: unknown) => typeof value === 'string' ? value : value == null ? '' : String(value);

export function PublicationStage({ workspace, onWorkspaceChange, onStageChange, onPersisted }: Props) {
  const [data, setData] = useState<PublicationStageData | null>(null);
  const [busy, setBusy] = useState(false);
  const [dirty, setDirty] = useState(false);
  const [error, setError] = useState('');
  const [assistant, setAssistant] = useState('');
  const [channelName, setChannelName] = useState('');
  const [channelType, setChannelType] = useState('direct');
  const [channelFormat, setChannelFormat] = useState('printed');
  const [taskText, setTaskText] = useState('');
  const [taskPhase, setTaskPhase] = useState('prelaunch');
  const [updateText, setUpdateText] = useState('');
  const [updateType, setUpdateType] = useState('correction');

  useEffect(() => { let alive = true; getPublicationStage(workspace.book.id).then((result) => alive && setData(result)).catch((cause) => alive && setError(cause instanceof Error ? cause.message : 'Não foi possível carregar a Publicação.')); return () => { alive = false; }; }, [workspace.book.id]);

  async function mutate(action: () => Promise<PublicationMutationResponse>) {
    if (busy) return; setBusy(true); setError('');
    try { const result = await action(); setData(result.publicationStage); setDirty(false); onWorkspaceChange(result.workspace); await onPersisted(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível concluir a operação.'); }
    finally { setBusy(false); }
  }
  function state(update: (current: PublicationState) => PublicationState) { if (!data || data.completed) return; setData({ ...data, state: update(data.state) }); setDirty(true); }
  async function save() { if (!data) return; await mutate(() => savePublicationStage(workspace.book.id, data.state, data.flags, data.finalConfirmation)); }
  async function assist(action: string) { setBusy(true); setError(''); try { const result = await assistPublicationStage(workspace.book.id, action); setAssistant(result.suggestion); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Não foi possível usar o Assistente de Publicação.'); } finally { setBusy(false); } }

  if (!data) return <section className="verbum-stage-content"><div className={`verbum-publication-state${error ? ' is-error' : ''}`}>{error || 'Carregando Publicação da Obra...'}</div></section>;
  const m = data.state.metadata; const pack = data.state.package; const launch = data.state.launch; const materials = data.state.materials; const release = data.state.release;

  if (data.completed) return <>
    <section className="verbum-stage-content verbum-publication-stage is-complete">
      <div className="verbum-publication-celebration"><span className="verbum-eyebrow">11 de 11 etapas concluídas</span><div className="verbum-publication-seal">100%</div><h2>Obra Publicada</h2><h3>{data.title}</h3><p>{text(data.state.identity.edition)} · Publicada em {data.publishedAt || 'data registrada'}.</p><code>{data.editionHash}</code></div>
      <div className="verbum-publication-stats"><article><strong>{data.formatCount}</strong><span>Formatos</span></article><article><strong>{data.channels.length}</strong><span>Canais</span></article><article><strong>{data.publishedChannelCount}</strong><span>Publicados</span></article><article><strong>{data.records.length}</strong><span>Registros</span></article><article><strong>{data.updates.length}</strong><span>Atualizações</span></article><article><strong>100%</strong><span>Workflow</span></article></div>
      <div className="verbum-publication-grid"><main>
        <Card title="Edição publicada" subtitle="Registro imutável da edição que chegou ao leitor."><div className="verbum-publication-readonly"><Read label="Título" value={m.title} /><Read label="Autor" value={m.author} /><Read label="Edição" value={m.edition} /><Read label="Arquivo" value={pack.finalFileUrl} /><Read label="Capa" value={pack.coverUrl} /><Read label="Hash da edição" value={data.editionHash} /></div></Card>
        <Card title="Canais publicados" subtitle="Links, identificadores e arquivo de referência de cada canal."><div className="verbum-publication-list">{data.records.map((record) => <article key={record.id}><div><strong>{record.channel}</strong><span>{record.format} · {record.publishedAt}</span>{record.url && <a href={record.url} target="_blank" rel="noreferrer">Abrir publicação</a>}</div><code>{record.fileReferenceHash.slice(0, 18)}…</code></article>)}</div></Card>
        <Card title="Atualizações pós-publicação" subtitle="Correções futuras ficam registradas sem apagar a publicação original."><div className="verbum-publication-new"><select value={updateType} onChange={(e) => setUpdateType(e.target.value)}>{data.updateTypes.map((o) => <option value={o.key} key={o.key}>{o.label}</option>)}</select><input value={updateText} onChange={(e) => setUpdateText(e.target.value)} placeholder="Descreva a atualização"/><button disabled={busy || !updateText.trim()} onClick={() => void mutate(() => registerPublicationUpdate(workspace.book.id, { type: updateType, description: updateText }).then((r) => { setUpdateText(''); return r; }))}>Registrar atualização</button></div><div className="verbum-publication-list">{data.updates.map((u) => <article key={u.id}><div><strong>{u.typeLabel}</strong><span>{new Date(u.createdAt).toLocaleString('pt-BR')}</span><p>{u.description}</p></div></article>)}</div></Card>
        <Card title="Nova edição" subtitle="Uma nova edição deve iniciar um novo ciclo editorial sem apagar o registro desta publicação."><p>A estrutura de histórico já preserva esta edição. A automação completa para clonar a obra em uma nova edição fica preparada para evolução posterior.</p></Card>
      </main><aside><History data={data} /></aside></div>
    </section>
    <WorkspaceFooter canGoBack onPrevious={() => onStageChange('legal')} onBackToLibrary={() => undefined} />
  </>;

  return <>
    <section className="verbum-stage-content verbum-publication-stage">
      <header className="verbum-publication-heading"><div><span className="verbum-eyebrow">Etapa 11 de 11</span><h2>Publicação da Obra</h2><p>Organize o pacote final, canais, metadados e o registro exato da edição publicada.</p></div><div className="verbum-publication-baseline"><small>Edição pronta para publicação</small><strong>{m.title}</strong><span>{text(data.legal.identity.edition)} · {text(data.legal.layout.format)} · {text(data.legal.identity.pageCount)} páginas</span><code>{data.legal.snapshotHash.slice(0, 18)}…</code></div></header>
      {!data.baselineValid && <div className="verbum-publication-warning"><strong>A baseline legal não está mais válida.</strong><p>Retorne aos Trâmites Legais antes de publicar.</p></div>}
      {data.consistencyWarnings.map((warning) => <div className="verbum-publication-warning is-soft" key={warning}>{warning}</div>)}
      {error && <div className="verbum-publication-state is-error">{error}</div>}
      <div className="verbum-publication-stats"><article><strong>{data.formatCount}</strong><span>Formatos</span></article><article><strong>{data.channels.length}</strong><span>Canais</span></article><article><strong>{data.publishedChannelCount}</strong><span>Publicados</span></article><article><strong>{data.resolvedRequiredCount}/{data.requiredChannelCount}</strong><span>Obrigatórios</span></article><article><strong>{data.tasks.filter((x) => x.status === 'done').length}/{data.tasks.length}</strong><span>Tarefas</span></article><article><strong>{data.progress}%</strong><span>Progresso</span></article></div>

      <div className="verbum-publication-grid"><main>
        <Card title="Pacote Final da Edição" subtitle="O arquivo e a capa usados na publicação ficam vinculados à baseline legal."><div className="verbum-publication-form cols-2"><Input label="Arquivo final" value={pack.finalFileUrl} disabled={data.completed} onChange={(value) => state((s) => ({ ...s, package: { ...s.package, finalFileUrl: value } }))} /><Input label="Capa final" value={pack.coverUrl} disabled={data.completed} onChange={(value) => state((s) => ({ ...s, package: { ...s.package, coverUrl: value } }))} /><Input label="Arquivo digital" value={pack.digitalFileUrl} disabled={data.completed} onChange={(value) => state((s) => ({ ...s, package: { ...s.package, digitalFileUrl: value } }))} /><Input label="Capa digital" value={pack.digitalCoverUrl} disabled={data.completed} onChange={(value) => state((s) => ({ ...s, package: { ...s.package, digitalCoverUrl: value } }))} /></div><div className="verbum-publication-readonly"><Read label="Hash legal" value={pack.legalSnapshotHash} /><Read label="ISBN/identificadores" value={Object.values(pack.isbn || {}).map((x) => text(x.number)).filter(Boolean).join(' · ') || 'Não aplicável/sem número'} /></div></Card>

        <Card title="Metadados da Publicação" subtitle="Dados comerciais independentes do corpo editorial da obra."><div className="verbum-publication-form cols-2"><Input label="Título comercial" value={m.title} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, title: value } }))} /><Input label="Subtítulo" value={m.subtitle} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, subtitle: value } }))} /><Input label="Nome do autor" value={m.author} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, author: value } }))} /><Input label="Descrição curta" value={m.shortDescription} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, shortDescription: value } }))} /><Textarea label="Descrição comercial" value={m.description} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, description: value } }))} /><Input label="Palavras-chave (separadas por vírgula)" value={m.keywords.join(', ')} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, keywords: value.split(',').map((x) => x.trim()).filter(Boolean) } }))} /><Input label="Categoria principal" value={m.primaryCategory} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, primaryCategory: value } }))} /><Input label="Categoria secundária" value={m.secondaryCategory} onChange={(value) => state((s) => ({ ...s, metadata: { ...s.metadata, secondaryCategory: value } }))} /></div></Card>

        <Card title="Estratégia de Preço" subtitle="Valores são organizacionais; taxas e receita líquida são apenas estimativas."><div className="verbum-publication-pricing">{Object.entries(data.state.pricing).map(([key, price]) => { const p = Number(String(price.price).replace(',', '.')); const c = Number(String(price.unitCost).replace(',', '.')); const fee = Number(String(price.channelFeePercent).replace(',', '.')); const net = Number.isFinite(p) ? p - (Number.isFinite(c) ? c : 0) - (Number.isFinite(fee) ? p * fee / 100 : 0) : 0; return <article key={key}><h4>{price.label}</h4><div className="verbum-publication-form cols-3"><Input label="Preço" value={price.price} onChange={(value) => state((s) => ({ ...s, pricing: { ...s.pricing, [key]: { ...s.pricing[key], price: value } } }))} /><Input label="Moeda" value={price.currency} onChange={(value) => state((s) => ({ ...s, pricing: { ...s.pricing, [key]: { ...s.pricing[key], currency: value } } }))} /><Input label="Custo unitário" value={price.unitCost} onChange={(value) => state((s) => ({ ...s, pricing: { ...s.pricing, [key]: { ...s.pricing[key], unitCost: value } } }))} /><Input label="Taxa estimada (%)" value={price.channelFeePercent} onChange={(value) => state((s) => ({ ...s, pricing: { ...s.pricing, [key]: { ...s.pricing[key], channelFeePercent: value } } }))} /><Read label="Receita líquida estimada" value={Number.isFinite(net) ? `${price.currency} ${net.toFixed(2)}` : '—'} /></div></article>; })}</div></Card>

        <Card title="Canais de Publicação" subtitle="Marque como obrigatório apenas os canais necessários para concluir esta edição."><div className="verbum-publication-new"><input value={channelName} onChange={(e) => setChannelName(e.target.value)} placeholder="Nome do canal"/><select value={channelType} onChange={(e) => setChannelType(e.target.value)}>{data.channelTypes.map((o) => <option key={o.key} value={o.key}>{o.label}</option>)}</select><select value={channelFormat} onChange={(e) => setChannelFormat(e.target.value)}><option value="printed">Impresso</option><option value="digital">Digital</option></select><button disabled={busy || !channelName.trim()} onClick={() => void mutate(() => createPublicationChannel(workspace.book.id, { name: channelName, type: channelType, format: channelFormat, required: true }).then((r) => { setChannelName(''); return r; }))}>Adicionar canal</button></div><div className="verbum-publication-list">{data.channels.map((channel) => <article key={channel.id}><div><strong>{channel.name}</strong><span>{channel.typeLabel} · {channel.format}</span><label><input type="checkbox" checked={channel.required} onChange={(e) => void mutate(() => updatePublicationChannel(workspace.book.id, channel.id, { required: e.target.checked }))}/> Canal obrigatório</label></div><div className="verbum-publication-channel-controls"><select value={channel.status} onChange={(e) => void mutate(() => updatePublicationChannel(workspace.book.id, channel.id, { status: e.target.value }))}>{data.channelStatuses.map((o) => <option key={o.key} value={o.key}>{o.label}</option>)}</select><input placeholder="URL da publicação" value={channel.url} onChange={(e) => void mutate(() => updatePublicationChannel(workspace.book.id, channel.id, { url: e.target.value }))}/><input placeholder="Identificador externo" value={channel.externalId} onChange={(e) => void mutate(() => updatePublicationChannel(workspace.book.id, channel.id, { external_id: e.target.value }))}/><input type="date" value={channel.publishedAt} onChange={(e) => void mutate(() => updatePublicationChannel(workspace.book.id, channel.id, { published_at: e.target.value }))}/><button className="is-danger" onClick={() => void mutate(() => deletePublicationChannel(workspace.book.id, channel.id))}>Excluir</button></div></article>)}</div></Card>

        <Card title="Lançamento" subtitle="Registre a data efetiva; o Verbum Studio não agenda publicação externa neste Sprint."><div className="verbum-publication-form cols-3"><label>Modo<select value={launch.mode} onChange={(e) => state((s) => ({ ...s, launch: { ...s.launch, mode: e.target.value } }))}><option value="immediate">Assim que disponível</option><option value="scheduled">Data específica</option></select></label><Input type="date" label="Data prevista" value={launch.plannedDate} onChange={(value) => state((s) => ({ ...s, launch: { ...s.launch, plannedDate: value } }))} /><Input type="date" label="Data efetiva" value={launch.actualDate} onChange={(value) => state((s) => ({ ...s, launch: { ...s.launch, actualDate: value } }))} /></div><Textarea label="Observações" value={launch.notes} onChange={(value) => state((s) => ({ ...s, launch: { ...s.launch, notes: value } }))} /></Card>

        <Card title="Plano de Lançamento" subtitle="Checklist leve de pré-lançamento, lançamento e pós-lançamento."><div className="verbum-publication-new"><select value={taskPhase} onChange={(e) => setTaskPhase(e.target.value)}>{data.taskPhases.map((o) => <option key={o.key} value={o.key}>{o.label}</option>)}</select><input value={taskText} onChange={(e) => setTaskText(e.target.value)} placeholder="Tarefa"/><button disabled={busy || !taskText.trim()} onClick={() => void mutate(() => createPublicationTask(workspace.book.id, { phase: taskPhase, description: taskText }).then((r) => { setTaskText(''); return r; }))}>Adicionar</button></div><div className="verbum-publication-list">{data.tasks.map((task) => <article key={task.id}><div><strong>{task.description}</strong><span>{task.phaseLabel}</span></div><button onClick={() => void mutate(() => updatePublicationTask(workspace.book.id, task.id, { status: task.status === 'done' ? 'pending' : 'done' }))}>{task.status === 'done' ? 'Reabrir' : 'Concluir'}</button><button className="is-danger" onClick={() => void mutate(() => deletePublicationTask(workspace.book.id, task.id))}>Excluir</button></article>)}</div></Card>

        <Card title="Materiais e Release Editorial" subtitle="Organize os materiais de apresentação sem alterar o conteúdo da edição."><div className="verbum-publication-form cols-2"><Input label="Imagem da capa" value={materials.coverImageUrl} onChange={(value) => state((s) => ({ ...s, materials: { ...s.materials, coverImageUrl: value } }))} /><Input label="Capa 3D" value={materials.cover3dUrl} onChange={(value) => state((s) => ({ ...s, materials: { ...s.materials, cover3dUrl: value } }))} /><Input label="Banner" value={materials.bannerUrl} onChange={(value) => state((s) => ({ ...s, materials: { ...s.materials, bannerUrl: value } }))} /><Input label="Link de compra principal" value={materials.buyLink} onChange={(value) => state((s) => ({ ...s, materials: { ...s.materials, buyLink: value } }))} /><Input label="Título do release" value={release.title} onChange={(value) => state((s) => ({ ...s, release: { ...s.release, title: value } }))} /><Textarea label="Resumo do release" value={release.summary} onChange={(value) => state((s) => ({ ...s, release: { ...s.release, summary: value } }))} /></div></Card>

        <Card title="Assistente de Publicação" subtitle="IA sugere. Autor decide. Nenhuma alteração é aplicada automaticamente."><div className="verbum-publication-actions">{[['description','Aprimorar descrição'],['keywords','Sugerir palavras-chave'],['categories','Sugerir categorias'],['bio','Aprimorar biografia'],['release','Criar release'],['launch','Checklist de lançamento'],['consistency','Conferir consistência']].map(([key,label]) => <button key={key} disabled={busy} onClick={() => void assist(key)}>{label}</button>)}</div>{assistant && <div className="verbum-publication-assistant-result">{assistant}</div>}</Card>
      </main><aside>
        <section className="verbum-publication-card"><div className="verbum-publication-card-head"><div><h3>Checklist Final</h3><p>{data.completedCount}/{data.total} concluídos</p></div><strong>{data.progress}%</strong></div><div className="verbum-publication-progress"><span style={{ width: `${data.progress}%` }} /></div>{data.checklist.map((item) => { const manual = !item.automatic && item.key !== 'completed'; const checked = manual ? !!data.flags[item.key] : item.completed; return <label className={`verbum-publication-check${checked ? ' is-complete' : ''}`} key={item.key}><input type="checkbox" checked={checked} disabled={!manual || data.completed} onChange={(e) => setData({ ...data, flags: { ...data.flags, [item.key]: e.target.checked } })}/><span>{item.label}</span></label>; })}</section>
        <section className="verbum-publication-card"><h3>Confirmação final</h3><label className="verbum-publication-confirm"><input type="checkbox" checked={data.finalConfirmation} onChange={(e) => setData({ ...data, finalConfirmation: e.target.checked })}/> Confirmo que os arquivos, metadados e canais obrigatórios desta edição estão corretos e que a publicação pode ser concluída.</label><button className="is-primary" disabled={busy || !data.ready} onClick={() => void mutate(() => completePublicationStage(workspace.book.id))}>Concluir Publicação</button></section>
        <History data={data} />
      </aside></div>
      <div className="verbum-publication-save"><button disabled={busy || !dirty} onClick={() => void save()}>Salvar agora</button></div>
    </section>
    <WorkspaceFooter canGoBack onPrevious={() => onStageChange('legal')} onBackToLibrary={() => undefined} />
  </>;
}

function Card({ title, subtitle, children }: { title: string; subtitle?: string; children: React.ReactNode }) { return <section className="verbum-publication-card"><div className="verbum-publication-card-head"><div><h3>{title}</h3>{subtitle && <p>{subtitle}</p>}</div></div>{children}</section>; }
function Input({ label, value, onChange, disabled = false, type = 'text' }: { label: string; value: string; onChange: (value: string) => void; disabled?: boolean; type?: string }) { return <label>{label}<input type={type} value={value || ''} disabled={disabled} onChange={(e) => onChange(e.target.value)}/></label>; }
function Textarea({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label>{label}<textarea value={value || ''} onChange={(e) => onChange(e.target.value)} /></label>; }
function Read({ label, value }: { label: string; value: unknown }) { return <div><small>{label}</small><strong>{text(value) || '—'}</strong></div>; }
function History({ data }: { data: PublicationStageData }) { return <section className="verbum-publication-card"><h3>Histórico</h3><div className="verbum-publication-history">{data.history.slice(0, 10).map((h) => <article key={h.id}><strong>{h.event}</strong><span>{new Date(h.createdAt).toLocaleString('pt-BR')}</span><p>{h.detail}</p></article>)}</div></section>; }
